### ISSUE TITLE
Trouble configuring pre-commit to run on Travis CI

### ISSUE THREAD

**Issue by jadchaar** [pre-commit/pre-commit#1044]
Hi, big fan of pre-commit, but I have been having some trouble setting it up for the `arrow` project. We are trying to enforce style requirements (e.g. black, flake8) on the codebase via pre-commit hooks, but I am having trouble configuring it to run on our Travis CI builds. I first tried setting the default language as Python 3, but then the build fails on all but the python 3.6 and 3.7 builds since pyenv is forcing the use of Python 3.5 for some reason.

Here is a link to the PR I am working with: https://github.com/crsmithdev/arrow/pull/587; and here are the Travis CI builds: https://travis-ci.org/crsmithdev/arrow.

Any help would be appreciated as I have been doing a lot of trial and error but have been unable to find the correct solution for using pre-commit on all our Python builds starting at 2.7.

For example, here is the latest build I am having trouble with: https://travis-ci.org/crsmithdev/arrow/builds/537337041. In this build, I set the language as python 3.7. When I set it as python 3, it does not work with python 2.7 and 3.5.

**Comment by asottile** [comment]
let me see what I can do for ya 👍

**Comment by jadchaar** [comment]
Thanks :). Been doing a lot of trial and error but cannot seem to nail down the root cause of this issue.

At a high level, we are creating a virtual env to run our tests in particular python versions, and we would like to run the pre-commit hooks with a python version >= 3.6 in order to be able to run black on all runs (even the python 2.7 runs).

**Comment by asottile** [comment]
makes sense, travis-ci usually only gives you one version of python per run so that might be tricky -- I seem to remember a way to enable more of them, let me try some stuff.

Another option would be to split out the lint job from the rest of the test jobs, but I think I can probably get the other one working for ya 👍

**Comment by jadchaar** [comment]
Either one would work! I really appreciate the help. I have been going at this for hours now haha!

**Comment by asottile** [comment]
no problem :D and go blue! (I graduated class of 2013!)

**Comment by jadchaar** [comment]
GO BLUE! That is amazing to hear :). Great to see a fellow wolverine maintaining some very useful open source projects--keep it up!

**Comment by asottile** [comment]
alright here's two options that work, I'll comment on the things I changed -- another option would be to switch travis-ci to use tox, let me know if you're interested in that and I can provide an example for that as well (with either approach)

### changes made in both things

- I cached the `pre-commit` directory as well as pip for speed
- I removed `sudo: false` (it hasn't done anything in a while)

### all jobs run `pre-commit` (a bit redundant imo)

- I had to add `language_version: python3.7` to black -- the upstream repo sets `language_version: python3` which then takes precedent over the `default_language_version` configuration setting
- I added a `pyenv global 3.7.1` call before the builds, this makes `python3.7` available as a command (so `pre-commit` can find it and install it)

```diff
diff --git a/.pre-commit-config.yaml b/.pre-commit-config.yaml
index 13adbb8..a3a69d4 100644
--- a/.pre-commit-config.yaml
+++ b/.pre-commit-config.yaml
@@ -34,6 +34,7 @@ repos:
       hooks:
           - id: black
             args: [--safe, --quiet, --target-version=py27]
+            language_version: python3.7
     - repo: https://gitlab.com/pycqa/flake8
       rev: 3.7.7
       hooks:
diff --git a/.travis.yml b/.travis.yml
index a824d98..3b90f2a 100644
--- a/.travis.yml
+++ b/.travis.yml
@@ -1,6 +1,8 @@
-sudo: false
 language: python
-cache: pip
+cache:
+    pip: true
+    directories:
+        - $HOME/.cache/pre-commit
 dist: xenial
 python:
     - 2.7
@@ -18,6 +20,7 @@ install:
     - if [[ $TRAVIS_PYTHON_VERSION == '3.7' ]]; then make build37; fi
     - if [[ $TRAVIS_PYTHON_VERSION == '3.8-dev' ]]; then make build38; fi
     - pip install -U codecov
+    - pyenv global 3.7.1
 script:
     # - if [[ $TRAVIS_PYTHON_VERSION == '3.7' ]]; then make lint-ci; fi
     - make lint-ci
```

### separate lint job (the one I'd probably go with personally)

- switched from `python: [list]` to `matrix: include: [list]` -- this allowed me to set more specific matrix entries
- `make "${TARGET:-test}"` is special bash syntax for "by default run `test` if `$TARGET` is missing or empty (I then only set `TARGET` for the lint matrix entry)

```diff
--- a/.travis.yml
+++ b/.travis.yml
@@ -1,14 +1,18 @@
-sudo: false
 language: python
 cache: pip
 dist: xenial
-python:
-    - 2.7
-    - 3.5
-    - 3.6
-    - 3.7
-    - 3.8-dev
 matrix:
+    include:
+        - python: 2.7
+        - python: 3.5
+        - python: 3.6
+        - python: 3.7
+        - python: 3.7
+          env: TARGET=lint-ci
+          cache:
+            directories:
+              - $HOME/.cache/pre-commit
+        - python: 3.8-dev
     allow_failures:
         - python: 3.8-dev
 install:
@@ -19,7 +23,5 @@ install:
     - if [[ $TRAVIS_PYTHON_VERSION == '3.8-dev' ]]; then make build38; fi
     - pip install -U codecov
 script:
-    # - if [[ $TRAVIS_PYTHON_VERSION == '3.7' ]]; then make lint-ci; fi
-    - make lint-ci
-    - make test
+    - make "${TARGET:-test}"
 after_success: codecov
```

### using tox

(I'd also suggest this)

let me know if you want me to set up a config for you, it'd look something similar to this: https://github.com/asottile/yesqa/blob/72a8010e694bfe52ffe43a344e213b3f2f85db2c/.travis.yml

**Comment by jadchaar** [comment]
Wow that is very elegant--I will definitely go with the second solution. I have a question about caching: if you add a caching entry for pre-commit like you did in the second solution, will the `pip` cache setting we have in the beginning of the file be supplemented or overriden (e.g. do we need to also add `$HOME/.cache/pip` to the lint-ci target)?

Also, do you recommend caching `pip` in general? I have seen some projects like pytest disable it, so I was wondering what you think about it.

I have been looking into tox a lot recently, but am wondering what perks it has over a Makefile. I'd love to hear about what it can offer :).

**Comment by asottile** [comment]
the matrix entry there overrides the base cache entry, you can make it still apply the `pip` cache by using `pip: true`, but it probably doesn't make it any faster 🤷‍♂ 

yeah in pytest we experimented with turning off the cache, for us it made a slight improvement (we download primarily pure python packages which have wheels on pypi -- the network from travis<=>pypi.org is fast enough that downloading everything always was faster than the cache download + extraction

on my travis projects (which are slowly being converted to azure pipelines due to higher throughput) I cache pip, though to be honest I haven't profiled the difference and I suspect I'd see similar things as we did in pytest.

at the bottom of it, if you have large binary dependencies that you have to build from source to use then it's probably worth it -- if you don't there's probably very little to no benefit for `cache: pip` / `cache: pip: true`

the main benefit to `tox` (I'm also a maintainer there, go figure) is that it does the virtual environment management for you.  It also is a bit more cross-platform-portable than `Makefile`s (you're unlikely to have access to a working `make` on windows for instance).  It's also a familiar choice for python developers.  I notice the `arrow` repository already has a `tox.ini` so in some capacity the work is partially completed.

**Comment by jadchaar** [comment]
Thanks for the great response and quick help @asottile! I will definitely explore `tox` going forward. The `arrow` tox file is quite outdated so it will require a bit of work to get up-to-date and on the same level as the Makefile.
