### ISSUE TITLE
Support post-checkout

### ISSUE THREAD

**Issue by domenkozar** [pre-commit/pre-commit#1120]
I know this goes beyond the original intention (and the name), but it would be really useful to be able to use same pre-commit hooks for different git hooks.

We need to run some validation before checking out. The alternative is to use https://github.com/sds/overcommit, but I'd prefer for pre-commit to get better.

**Comment by asottile** [comment]
sure! there's already a few other `git` hooks supported and it shouldn't be too much work to add another one -- would you like to take a stab at it?  here's where `prepare-commit-msg` was added for example: https://github.com/pre-commit/pre-commit/pull/1004

given the others are currently file-based there might need to be some design aspects to this particular hook since `post-checkout` doesn't really operate on files

**Comment by asottile** [comment]
oh right -- this got released as part of [2.2.0](https://github.com/pre-commit/pre-commit/releases/tag/v2.2.0) -- thanks again for the issue!
