### ISSUE TITLE
Support for remote docker engine (CircleCI)

### ISSUE THREAD

**Issue by michaelfarrell76** [pre-commit/pre-commit#1126]
Hi there, I've been a big fan of pre-commit!

We've recently switched from TravisCI to CircleCI, mainly for the ability to run our CI workflow from a pre-built docker image. This drastically speeds up the workflow, however has introduced some issues with pre-commit against a docker entry-point.

When i run pre-commit i get the following error:

```
packages/backend/docker/app.Dockerfile: openBinaryFile: does not exist (No such file or directory)
```
	
<img width="888" alt="Screen Shot 2019-08-29 at 6 40 32 PM" src="https://user-images.githubusercontent.com/10264973/63987320-92e19400-ca8c-11e9-936b-8e0d9025e047.png">

This is likely due to the fact that [running docker on CircleCi](https://circleci.com/docs/2.0/building-docker-images/#section=configuration) (using the `setup_remote_docker` command) actually boots up a remote docker engine where it executes, separate from the locally cloned git repository. Since this is executing in a separate instance, pre-commit fails to locate the files. (not sure about this analysis, just a prediction)

CircleCI does not allow file mounting, but it does allow the ability to [copy your local files](https://circleci.com/docs/2.0/building-docker-images/#mounting-folders) into the remote docker instance so that the folder structure can be a mirror of the repository pre-commit is running against.

I've struggled to find documentation anywhere online of using pre-commit docker entries with CircleCI, and the abstraction that pre-commit uses makes it difficult for me to figure out what docker copy command i should run to mirror the docker environments that are executing the pre-commit scripts.

In our scenario, it is nice to use docker entries locally so that developers on our team do not need to install all necessary dependencies, but it would be ideal if there was some sort of flag on pre-commit that would disable the use of docker images on the CI and instead require that all of their dependencies are pre-installed on our CI docker image.

Another option would be figuring out how to support remote docker engines (or pointing me in the direction of where I could figure this out).

To wrap it up, I understand this may not be something solvable from pre-commit's end, but I wanted to ask if there is a known solution, and document the issue I am having with pre-commit + CircleCi + docker entry in case others end up in the same situation.

**Comment by asottile** [comment]
yeah this seems pretty tricky

I don't know quite how circle is supposed to work here, from the docs it looks like what they're doing is setting up a shared volume and using `docker cp` to populate that volume.  then after that you'd use `docker run --volumes-from` to inherit those volumes later

I don't see a way that you could inject this into `pre-commit`, mostly because `pre-commit` assumes it can `-v` mount from the host filesystem and have that work.  The particular code in question lives here: https://github.com/pre-commit/pre-commit/blob/96c35185f07925ff10a04e3d161c96baf39eaa28/pre_commit/languages/docker.py#L91

In this code it's volume mounting the current working directory to `/src`

In theory you could probably do the same volume population that's suggested in the documentation, the hard part would be making that work with `pre-commit` -- notably the `docker` code above would need to know that it should use `--volumes-from` instead of `--volume`.  I'm not seeing a good way to integrate that off the top of my head but maybe it'll give you something to play around with in a fork?

Reading the procedure on that documentation page, it looks like what they do is spin up a long-running container that's used to house volumes, and that lives onwards and is used as a volume store 🤔 

I myself haven't worked with circleci in quite a while, but I've had good experiences using docker on azure pipelines, that might be another option for you to try (don't really want to be like, yeahhh just switch your CI pipeline to a competitor) but it's a potential option for you.

Happy to give you more pointers into how you would go about implementing this!

**Comment by michaelfarrell76** [comment]
wow super quick response, thanks so much.

my current workaround is to just turn off the two pre-commit steps that use docker images:
`SKIP: shellcheck-lint,dockerfile-lint`

but thanks for the reference in the code, I will probably play around at some point and I'll post back if I have any luck!

**Comment by asottile** [comment]
sounds good, since I don't think there's anything much more actionable from our side here I'm going to close this out -- feel free to comment back if you find anything else (or anything that's worth documenting)! -- thanks again for the issue 🎉
