### ISSUE TITLE
Support configuring run-time environment options generically

### ISSUE THREAD

**Issue by eigengrau** [pre-commit/pre-commit#1157]
It would be useful if we could configure certain aspects of the run-time environment from which hooks are run. E.g., I would find it awesome if I could:

- set arbitrary environment variables for some or all hooks that are run
- source a piece of shell-code before a hook is run
- switch into a subdirectory of the repository before running the hook’s entry-point

My immediate use-case is to work-around https://github.com/ansible/ansible-lint/issues/245, which would require both custom environment variables as well as switching the working directory. However, I expect that this would be great to have for other situations, as well.

E.g., while pre-commit does a great job of isolating a hooks environment by installing all dependencies of a Python-hosted hooks in an isolated location, a lot of my co-workers are using outdated distributions resp. Python installations. To keep our workflow as uniform as possible, I take steps which will create repository-local installations of Python, Node.js and other run-times. For working on the command-line, I usually rely on [direnv](https://direnv.net) to install any run-times and to adjust the user’s `PATH` so that repository-local installations are used. It would be great if I could configure pre-commit so that, prior to running any hook, pre-commit would source a script of my choosing.

Thank you for making pre-commit!

**Comment by asottile** [comment]
you can do that with `env`  or `bash`-- this is already demonstrated here: https://github.com/pre-commit/pre-commit/issues/758#issuecomment-404554291

**Comment by eigengrau** [comment]
Thank you for the pointer! I guess overriding the entrypoint should work out in our case, even though it increases the coupling between configuration and hook. It’s a bit problematic that the entrypoint is not passed through a shell. Going via `bash -c` adds another level of quoting, so a generic mechanism would be great. Alternatively, having the entrypoint command pass through a shell (perhaps optionally) would be useful. If you think that’s something worth having I could see if I can find some time to look into the code.

**Comment by asottile** [comment]
> It’s a bit problematic that the entrypoint is not passed through a shell

well for a couple reasons:
- shells mean shell injections mean CVEs, no no no
- pre-commit is cross platform where you may not have a consistent shell (windows, macos, future macos, etc.)

> Going via `bash -c` adds another level of quoting, 

you'd have the same level of quoting either way as you have to make a shell command.  yaml supports bare words so you probably don't need anything tricky here anyway

> Alternatively, having the entrypoint command pass through a shell (perhaps optionally) would be useful. If you think that’s something worth having I could see if I can find some time to look into the code.

thanks for the suggestion, but no (as per above)

pre-commit has a golden path which is where pre-commit manages all the environments and dependencies.  when you start to step outside that you're going to need to do tricky things -- pre-commit is not going to support those directly because it steps outside the bounds of the happy path (requiring extra setup on the user's side, etc.)
