### ISSUE TITLE
[suggestion] absolute-git-dir vs show-toplevel

### ISSUE THREAD

**Issue by ammarnajjar** [pre-commit/pre-commit#1226]
I would suggest using `git rev-parse --absolute-git-dir` instead of `git rev-parse --show-toplevel` to find the git-root directory.

Reasoning:

- #1219 caused some hassle, where `--absolute-git-dir` works from anywhere inside a git repo ([docs](https://git-scm.com/docs/git-rev-parse#Documentation/git-rev-parse.txt---absolute-git-dir)), including `.git` and its subtree.
- the output is processed as a string afterwards anyway, so removing the basename (`.git`) won't be an issue: 
https://github.com/pre-commit/pre-commit/blob/bb108bf00e8a19bfb41a32afae7c4a9a58a56866/pre_commit/git.py#L40 
https://github.com/pre-commit/pre-commit/blob/bd212393ae0ba0086e6df788a1fb683cb06ac3d3/pre_commit/resources/hook-tmpl#L78-L79
- one `if` branch less: https://github.com/pre-commit/pre-commit/blob/023b337ff0f5566f366dd85c390804208a60f7e7/pre_commit/main.py#L131-L137

I can give the implementation a shot, if approved 😄

**Comment by asottile** [comment]
`absolute-git-dir` and `toplevel` are two entirely separate concepts -- there is also no guarantee that `.git` is at the root of the repository (consider submodules / subtrees / etc.)

`--show-toplevel` is the correct value for "I want to be at the root and access the files" -- it just happens to be nonsense when inside `.git`

we do use `--git-common-dir` / `--git-dir` to install the hooks (since that moves based on subtree / submodules) -- and you have to worry about the git version which they're supported in as well

**Comment by ammarnajjar** [comment]
Oh, that was on my blind spot 😅 , thanks for the quick response and explanation!

**Comment by asottile** [comment]
no problem! thanks for the issue nonetheless :)
