### ISSUE TITLE
support for `flake8 --diff`, which checks only the diff in the commit

### ISSUE THREAD

**Issue by koreno** [pre-commit/pre-commit#1279]
when flake8 is passed the `--diff` flag, it expects stdin to provide it with the code to lint, instead of as filenames.
It would be nice to add to pre-commit support for such hooks, in the form of a `pass_diff=True` hook parameter.

**Comment by asottile** [comment]
pre-commit has no such mode for that, pre-commit operates on *files*.  doing this directly in the framework doesn't really make sense (what would `pre-commit run --all-files` do?)

however you could implement a small wrapper script which invokes flake8 in that way:

```python
# untested, probably needs tweaking (written in github comment box)
import subprocess
import sys

def main() -> int:
    diff = subprocess.run(
        ('git', 'diff', '--staged', '--', *sys.argv[1:]),
        stdout=subprocess.PIPE,
    ).stdout
    return subprocess.call(('flake8', '--diff'), input=diff)

if __name__ == '__main__':
    exit(main())
```

(additionally, `--diff` mode is meant to be a temporary measure in flake8, it's best to get linting passing and not use that option)

if you're looking for ways to gradually add linting to a repository (which is what `--diff` was designed to do) you'll probably find `files` / `exclude` more helpful (get a part of the codebase passing, add it to `files` or the opposite with `exclude`)

**Comment by asottile** [comment]
also note that `flake8 --diff` isn't faster flake8 still lints everything and then after that trims down the output.  additionally, `flake8 --diff` can still allow lint errors to creep into your codebase as touching lines can cause lint errors on other lines so it's not exactly the safest gate keeper. (I'm also a maintainer of flake8)

**Comment by koreno** [comment]
> pre-commit has no such mode for that, pre-commit operates on _files_. doing this directly in the framework doesn't really make sense (what would `pre-commit run --all-files` do?)
"--all-files" could ignore hooks that ask for diff, or if we really wanted, implement a more sophisticated spec that tells per-commit what to do with the hook in each mode. Might be right for "completeness", but I don't feel that's important.

> wrapper script

That might be the way to go...



> gradually add linting to a repository

I'm aware of that, but that's not enough... When people are stressed about solving bugs and adding features, and aren't big fans of style-guided, having to go over someone else's non compliant code is just too much. In addition, it make for hellish code-reviews, where the reviewers don't know which changes are there to pacify the linter, and which are the actual logic changes. git-blame also suffers.
For all these reasons I feel the 'diff-only' is quite important for the success of pre-commit, at least in the places I work at...

**Comment by asottile** [comment]
invest the time to fix the code once, it'll be worth the hassle later -- even with `flake8 --diff` you'll still often have to mix lint fixes with functional changes (say you touch a line without style compliance)

anyway, thank you for the issue but due to the ergonomics of this outside of just commit time (where I agree there's a potential use case) I don't think it is doable

**Comment by asottile** [comment]
note also that `pre-commit` already does some pruning of files sent to hooks, for example during `commit` it will only [send the staged files](https://pre-commit.com/#pre-commit-during-commits)

**Comment by asottile** [comment]
@koreno it seems this satisfies your requirements without needing a script as well:

```yaml
-   repo: https://gitlab.com/pycqa/flake8
     rev: 3.7.9
     hooks:
     -   id: flake8
        entry: bash -c 'git diff --staged -- "$@" | flake8 --diff' --
```

**Comment by koreno** [comment]
ah, excellent, thank you!

**Comment by asottile** [comment]
cheers! 🎉 -- thanks for the issue

**Comment by Mahdi-Hosseinali** [comment]
I had this legacy repo with a huge amount of flake8 violations. There are obsolete modules that cannot be tossed because the logic would be salvaged at some point. The best way I found is to dump the flake8 issues into a file. Then write a script that reads that file and counts the number of codes per file, run flake8 and calculate the code issues per file. The script can compare the two to make sure no new code is being created for a file and exit with a non-zero code if so. If no new issues are made in a file, then it's all good and the tracking file can be updated with the current issues. You can run the script in a pre-commit hook and add the file to the staging area. This way you know each commit is a step forward and people are not adding more bad code just because you cannot track the old one.

The downside is that it might not be easy to track what new problems have been raised. The only guarantee is that you know for example F401 is increased in file a.py by 2, trying to go for anything more general can become complex fast. The other thing you should note is to have a post-pr-merge github action to update this tracking file because of obvious reasons.
