### ISSUE TITLE
core.hooksPath being set makes it not possible to install

### ISSUE THREAD

**Issue by damienrj** [pre-commit/pre-commit#1298]
I have a laptop which has some mandaotry global settings for git, and I have not been able to enable pre-commit.  I also tried doing
```
git config --global init.templateDir ~/.git-template
pre-commit init-templatedir ~/.git-template
```
But still get the message
```
[ERROR] Cowardly refusing to install hooks with `core.hooksPath` set.
hint: `git config --unset-all core.hooksPath`
```

Is there any work arounds for this?

**Comment by asottile** [comment]
I believe #1198 #718 #663 pre-commit/pre-commit-hooks#250 have more information on this

the problem is twofold: writing outside of the controlled directories has all sorts of implications that I don't really want to be involved in, the setting can lead to hooks not being executed when they should be

it is a little weird that `init-templatedir` complains about that though -- though this is most likely due to the code sharing between `install` and `init-templatedir`

let me see if that can be changed to better accommodate this :thinking:

**Comment by asottile** [comment]
could you try #1299 and see if helps your usecase?

**Comment by damienrj** [comment]
Yeah, I will try that. Thanks!

**Comment by damienrj** [comment]
I did 
```
pip install git+git://github.com/pre-commit/pre-commit.git@d56fdca618197c68937387292de0dcc19224068d
```
and I still get the same message. I confirm that I see the 
```
[init]
	templateDir = /Users/damien/.git-template
```
In my ~/.gitconfig

**Comment by asottile** [comment]
what command are you running?

**Comment by asottile** [comment]
you may need to `pip uninstall pre-commit` first before installing from `git`

**Comment by damienrj** [comment]
I did
```
pip uninstall pre-commit
pip install git+git://github.com/pre-commit/pre-commit.git@d56fdca618197c68937387292de0dcc19224068d
git config --global init.templateDir ~/.git-template
pre-commit init-templatedir ~/.git-template
```
And it looks like adding the uninstall step did make it work!

**Comment by asottile** [comment]
cool
