### ISSUE TITLE
[Proposal]How about to automate installation of hook script after pre-commit's installation

### ISSUE THREAD

**Issue by m-shaka** [pre-commit/pre-commit#1304]
It can be realized by passing custom install class to setup function in setup.py.

**Comment by asottile** [comment]
this is a *really bad idea* and a good way to get your package banned -- arbitrary code execution in `setup.py` is an anti-feature and should not be abused in this way.  in particular, this is one of the advantages over the shenanigans that npm packages do upon installation

but for the memes, I went ahead and implemented this just to show how bad it is:
- you can't distribute a wheel (no code is executed for a wheel)
- you need to actively *break* wheeling (otherwise pip will only run your arbitrary code once)
- you can't do it portably (pip installs in a temporary directory which makes it very difficult to find the target installation directory)
- there's no indication that it happens (pip hides the output, except for the failed wheeling)
- I streamed writing this on [my twitch](https://twitch.tv/anthonywritescode) but unfortunately that was before I re-uploaded to youtube so you can't see my utter horror as I wrote the monstrosity

anyway, disclaimers aside, please don't use this it's awful: https://github.com/pre-commit/pre-commit-installed

**Comment by m-shaka** [comment]
I appreciate your detail explanation! I know what you mean.
