### ISSUE TITLE
[FR]: Add option to use a custom config file during `pre-commit install`

### ISSUE THREAD

**Issue by pat-s** [pre-commit/pre-commit#1307]
This would enable the possibility of using a central custom config file globally when installing `pre-commit` in new repos.

See https://github.com/lorenzwalthert/precommit/issues/85#issuecomment-580837182

## Proposal

- `pre-commit install --config https://raw.githubusercontent.com/path/to/raw/.pre-commit-config.yaml`
- `pre-commit install --config file:///abs/path/to/config-1.yaml`

**Comment by asottile** [comment]
did you try your suggestion? it already works

```console
$ cat t.yaml 
repos:
-   repo: meta
    hooks:
    -   id: identity
$ pre-commit  install --config t.yaml 
pre-commit installed at .git/hooks/pre-commit
$ git commit -m "foo" --allow-empty
identity.............................................(no files to check)Skipped
- hook id: identity
[py2_cleanup_more c6c77cb] foo
```

**Comment by rsb-23** [comment]
> did you try your suggestion? it already works
> 
> ```
> $ cat t.yaml 
> repos:
> -   repo: meta
>     hooks:
>     -   id: identity
> $ pre-commit  install --config t.yaml 
> pre-commit installed at .git/hooks/pre-commit
> $ git commit -m "foo" --allow-empty
> identity.............................................(no files to check)Skipped
> - hook id: identity
> [py2_cleanup_more c6c77cb] foo
> ```

..but `$ pre-commit run` still looks for `C.CONFIG_FILE` instead of `t.yaml`.
- Can we modify the default value of [args.config](https://github.com/pre-commit/pre-commit/blob/main/pre_commit/main.py#L51) to --config value during install?  

Reason: If a user is using `t.yaml` for installation, then mostly he/she does not have `C.CONFIG_FILE`. Also, it would be better if we don't have to pass config arg after install.

**Comment by asottile** [comment]
`pre-commit run` also takes `--config`

**Comment by asottile** [comment]
and no, if you want to intentionally violate the convention you get to live with the consequences
