### ISSUE TITLE
Configurable maximum parallel files

### ISSUE THREAD

**Issue by Yajo** [pre-commit/pre-commit#1374]
I have a hook that only supports 1 file input. It's [this little friend](https://github.com/Lucas-C/pre-commit-hooks-nodejs/blob/b234899b5db911d0e5482deffcf4e6364ad349d0/.pre-commit-hooks.yaml#L20-L26), which uses [markdown-toc](https://github.com/jonschlinkert/markdown-toc) behind the scenes.

That script is very useful, but it only supports formatting 1 fiile at a time.

Current options are:

1. `require_serial: yes`, in which case it will autodivide the number of files. You can be lucky and have pre-commit passing a single file, or unlucky and have pre-commit passing more than one, making the hook fail always.
1. `require_serial: no`, in which case pre-commit will send all files at once to the hook. Bad also.

I miss this option: `max_parallel_files`, which could be set to 1 so we make sure that parallel (or not) execution never gives the hook more than 1 file to format.

**Comment by asottile** [comment]
#394 is the duplicate for this

pre-commit's stance on this is that linters/formatters which only take one file at a time are malformed.  calling a linter once per files prohibitively expensive (especially on windows) and should be fixed in the tool itself to take multiple arguments

there is a workaround in the linked ticket, but pre-commit will not make this an option as it enables a sub-par user experience and adds complexity to do so

the parallel / serial options are unrelated to the number of files -- they are about how many parallel processes are used to run the hooks

**Comment by asottile** [comment]
for what it's worth, [`doctoc`](https://github.com/thlorenz/doctoc) doesn't have this problem
