### ISSUE TITLE
Separate each hooks' dependencies

### ISSUE THREAD

**Issue by jtmiclat** [pre-commit/pre-commit#1401]
Hi, thank you for a wonderful project! It is incredibly useful!

I was wondering if there is a way to separate the dependencies within a repo?

Right now we have a singular repo that has multiple hooks. When we install 1 hook we have to install all hooks for that language. For example`.pre-commit-hooks.yaml` looks like:
```
- id: black
   ...
  entry: black
  language: python
  types: [python]
- id: flake8
  ...
  entry: flake8
  language: python
  types: [python]
```
And our `setup.py` includes 
```
setup(...,install_requires=[
    "black==19.10b0",
    "flake8==3.7.9",
 ])
```

I was wondering if there was a way to maintain a singular repo for all hooks while having each hook's dependencies separate? Maybe having a different setup.py or package.json for each hook?

**Comment by asottile** [comment]
if you use `additional_dependencies` to install the things instead of setup.py it'll make separate environments for them -- though I don't know why you would duplicate the work that's already done for you in black's config and flake8's config? (your configs above have some bugs that are solved there fwiw)

**Comment by jtmiclat** [comment]
Alright! That makes sense. black and pre-commit are the current hooks I have but if I plan to add some custom linter or formatters and wanted to know how to control the dependencies. Thanks a lot!
