### ISSUE TITLE
How to see the actual hook command being executed?

### ISSUE THREAD

**Issue by ahakanbaba** [pre-commit/pre-commit#1446]
Is there a DEBUG-like option to see the actual commands being executed for a hook?

For example I have a mypy hook 
Enabled like this in the `.pre-commit-config.yaml` file

```
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.701
    hooks:
    -   id: mypy
```

When I run `pre-commit run --all-files --verbose`
The relevant output is:

```
mypy.....................................................................Passed
- hook id: mypy
- duration: 0.92s
```

Is there an option to see the actual mypy command ? 
It would be different inside pre-commit but I am looking to see something like the following

```
mypy --show-column-numbers  --shadow-file ..../app/services/job_scheduler.py.  /var/f
olders/r2/x60ktwlx5mvb8zyv31b4tvxh0000gp/T/vathVbh/4/job_scheduler.py ..../app/services/job_scheduler.py
```

I hope I may ask a usability question here. If github issues is not the right platform for questions please redirect me to the right place.

**Comment by asottile** [comment]
there is not as the command [will always be `entry` + `*args` + `*filenames`](https://pre-commit.com/#passing-arguments-to-hooks)

if you're unsure, you can test a similar hook [by using the `identity` hook (which prints its positional arguments)](https://pre-commit.com/#meta-hooks)

**Comment by james-johnston-thumbtack** [comment]
@asottile I second the desire for basic debugging information to be outputted with `--verbose`, such as listing the tool command lines that are actually being invoked.

> there is not as the command [will always be entry + *args + *filenames](https://pre-commit.com/#passing-arguments-to-hooks)

Sure, I understand this in principle.  But what are the `filenames`?  Did pre-commit detect/match them correctly and pass to the tool?  Did the arguments get assembled correctly?  Can I save some time by looking at debug logs?  Apparently not, [because you intentionally want to hide and obscure the operation of this tool as much as possible because us end-users can't be trusted?](https://github.com/pre-commit/pre-commit/issues/1916#issuecomment-844285549)  I don't want to figure out how to modify the config file with "identity" hook or whatever, that is needlessly complicated and also results in a _different_ configuration from the one I am debugging so how would I know it is yielding accurate information.

In general, debug logs are a useful tool to yield accurate diagnostics / validations, as an alternative to "RTFM and/or reverse engineer the code."  This is the first open source tool I've used that intentionally hides information from users because they can't be trusted to look at diagnostic/debug information.  That's wild, and incredibly condescending.
