### ISSUE TITLE
Global hooks (core.hooksPath)

### ISSUE THREAD

**Issue by hoshsadiq** [pre-commit/pre-commit#1473]
considering this #718 was merged to address #663 , is there a way to run global hooks currently? If not, would it be possible to request this as a feature?

**Comment by asottile** [comment]
[`pre-commit init-templatedir`](https://pre-commit.com/#pre-commit-init-templatedir) is the designed interface for globally enabling hooks.

`core.hooksPath` has several problems as you can read in these issues: https://github.com/pre-commit/pre-commit/issues?q=is%3Aissue+core+hooksPath+is%3Aclosed

**Comment by hoshsadiq** [comment]
So I guess my point was more to have hooks that are read globally among all repositories, not one that is copied over into the repository on clone.

The reason, in my opinion, `init-templatedir` isn't good enough (if I'm understanding it correct that is), is because that specifically specifies a directory of git hooks (let's image we ran `git config --global init.templateDir ~/.git-template`). When a repo is cloned, and `pre-commit install` is run, it will copy those hooks over, so they can be used. Unfortunately though, if I were to make a chance to a hook in `~/.git-template`, this change would not reflect in the repositories that have already been cloned.

Hope that makes sense.

**Comment by asottile** [comment]
the design of the pre-commit framework is a rejection of globally managed things -- it simply doesn't work in practice (you can never upgrade things without breaking everything).  that said, there are some ways you can simulate it: https://github.com/pre-commit/pre-commit/issues/450#issuecomment-405616722 (see also the linked issues here: https://github.com/pre-commit/pre-commit/issues/731#issuecomment-376945745)

**Comment by l3d00m** [comment]
Hey @hoshsadiq, I think I have a similar use case as yours. I'm not looking to enforce specific hooks for all repos (in fact, I have no problem with adding the yaml file to each repo using the great [all-repos](https://github.com/asottile/all-repos)), but rather I'm looking for a way to centrally (on each machine) manage the githook that is created by `init-templatedir`.

My reason for that is that a lot of repos already exists on the dev's machine and requiring devs to run `pre-commit install` for all repos is a lot of work. Also it will be a pain if I ever had to force all devs to run `pre-commit install` again **in all existing repos** because I made some changes to the behaviour of `init-templatedir` (which might happen in my use case).

For that reason I decided the best way forward is to run the following commands on all dev machines (idea is from #1198, thansk to @janosh):
```bash
git config --global core.hooksPath ~/.git-template
pre-commit init-templatedir ~/.git-template
```
and then add hint that if devs have already existing local hooks in specific repos, they'll need to execute the following for each of those repos (which aren't a lot normally):
```bash
git config --local core.hooksPath .git/hooks
cp ~/.git-template .git/hooks # doing it like this since pre-commit install refuses to install with core.hooksPath set
```
I'm currently still evaluating if this solution will work or if I'm missing something important, but so far it looks good. If you've found another way, feel free to share, I'm currently in need for inspiration on this.

---
And btw @asottile thanks a lot for maintaining this! The tool's really helpful for me and I can't imagine how exhausting it must be to answer questions on (and justify) certain design decision over and over again.

**Comment by xeruf** [comment]
I am appalled how all objections in #1198 are squashed and `pre-commit` making it stupidly hard to force it to coexist with a globally set `core.hooksPath`. Valid use-cases are mentioned there, and removing the globally set config to run pre-commit install and then setting it again is not acceptable. I do not understand why there is no `--force` or override or whatever flag.

**Comment by xeruf** [comment]
Found an automatable solution:
```sh
❯ git config --unset core.hooksPath
❯ GIT_CONFIG_GLOBAL=/dev/null pre-commit install
pre-commit installed at ...
❯ git config --add core.hooksPath .git/hooks
```
