### ISSUE TITLE
Possible to configure a hook so pip installs "extras"?

### ISSUE THREAD

**Issue by max-sixty** [pre-commit/pre-commit#1526]
When isort is installed as part of a pre-commit hook, it needs to be installed with setuptools' ["extras" for `pyproject`](https://github.com/timothycrosley/isort/blob/4e4d92931cc814a6544db102343910eb8002055a/pyproject.toml#L42).

This is installed with `pip install isort[pyproject]` rather than the default install of `pip install isort`. When installing from a local repo, the command is `pip install .[pyproject]`

Is it possible to specify that in a `.pre-commit-hooks.yaml`?

Ref https://github.com/timothycrosley/isort/issues/1225

Thank you!

**Comment by asottile** [comment]
I believe you're looking for [`additional_dependencies`](https://pre-commit.com/#config-additional_dependencies)

**Comment by asottile** [comment]
specifically:

```yaml
-   id: isort
    additional_dependencies: ['.[pyproject]']
```

or whatever extra you want

**Comment by glasserc** [comment]
Ah, this used to bite me all the time! This solution (`.[extra]`) is a lot nicer than anything I ever came up with. I wonder if it's worth noting this trick in the docs somewhere? I guess it's low priority because `isort` no longer has these set up as `extras`, but still, this is a really nice solution and I feel like it should be more visible.
