### ISSUE TITLE
No git version detection or labels

### ISSUE THREAD

**Issue by JimCircadian** [pre-commit/pre-commit#1534]
Hello there

With both 2.2.0 and 2.6.0 I had quite an odd error which ended up being down to the standard git version in CentOS v7. I had a look around and I couldn't see any mention of version numbers obvious in documentation and changelog!

I think it might be suitable to add a check into the command to specify when an invalid version of git is being used. If there's an appetite for this I'd happily contribute.

Linked issue: https://github.com/dask/dask/issues/6401

Please let me know your thoughts!!!

**Comment by asottile** [comment]
in general when you use 8 year old software (git 1.8) you're probably going to have a bad time.  that said, if you add `.git` to the end of the url iirc that old version of git works better.  this is because git 1.x has a few problems with libgit's protocol implementation (this is the one github uses)

it's not really a problem of pre-commit but of git/github itself

pre-commit does not check the git version explicitly because (1) it is slow and (2) it is error prone.

**Comment by asottile** [comment]
your problem is also probably fixed if you install from a tag and not a branch -- note that installing from a branch [is not a supported workflow](https://pre-commit.com/#using-the-latest-version-for-a-repository) though works by coincidence

it may also be possible to fix this if you're willing to invest some work into it -- as detailed [here](https://github.com/pre-commit/pre-commit/issues/1211#issuecomment-555228323)

**Comment by JimCircadian** [comment]
Thanks for the feedback @asottile, much appreciated :-)
