### ISSUE TITLE
Support for conda environment.yml files in requirements-txt-fixer

### ISSUE THREAD

**Issue by joshowen** [pre-commit/pre-commit#1551]
It would be very helpful if the requirements-txt-fixer supported conda's environment.yml file format for both pip and conda requirements.  These are being used more widely in the scientific computing community.

**Comment by asottile** [comment]
oh, I commented before your edit.  `requirements-txt-fixer` is specific to `requirements.txt` files and shouldn't / wouldn't handle conda's environment file.

I'd suggest writing a new tool which handles that separately instead instead of conflating the two into one tool

I'll move this issue back since it's now clear that you're referring to a particular pre-commit hook
