### ISSUE TITLE
Flake 8 - BUG: expected environment for python to be healthy() immediately after install

### ISSUE THREAD

**Issue by arxcruz** [pre-commit/pre-commit#1578]
I saw there's an issue #1575 that was fixed recently, however, flake is having the same error.

You may check logs here https://17ac62f25a31b1234b98-52f9a55e019565a745f2bb8d45b0d6fa.ssl.cf5.rackcdn.com/745120/6/check/openstack-tox-pep8/ad2c7a6/job-output.txt

We are already using pre-commit 2.7.1 that should have the #1575 patch.

**Comment by ssbarnea** [comment]
That bug is not really what it seams, it can happen if an older virtualenv is installed. If you add a `pip check` before running pre-commit, it will report a conflict like
```
pre-commit 2.7.1 has requirement virtualenv>=20.0.8, but you have virtualenv 16.7.10.
```

While this is a deployment issue it incovers the fact that pre-commit (stacktrace) behavior is confusing. Instead it would be preferable to just call a pip check itself in order to provide a more useful error.

**Comment by asottile** [comment]
yep, you have an incompatible version of virtualenv:

> virtualenv==16.7.5
