### ISSUE TITLE
per-hook `from_ref: rev` setting

### ISSUE THREAD

**Issue by graingert** [pre-commit/pre-commit#1584]
currently you can set `--from-ref` globally, but I'd ideally like to be able to set it per-hook in the config file

To progressively upgrade legacy projects with file based auto-fixers

**Comment by asottile** [comment]
sorry not going to implement this

the recommended approach is to format all your files in one go, this is a better experience anyway as you:
1. get the conflicts all out of the way
2. have a single commit to ignore in blame instead of many
3. changes to files don't trigger unrelated formatting

alternatively you can opt in chunks of your codebase via files

there's also the global option which already does what you want, implementing this on a per-hook basis is too specific and will add too much complexity (and will be very slow!)
