### ISSUE TITLE
always_run vs pass_filenames?

### ISSUE THREAD

**Issue by TylerYep** [pre-commit/pre-commit#1638]
I am using pre-commit for both mypy and pytest, but I had a few questions about how pre-commit works.

I want to run mypy over all files, not just changed files, because changing the type annotations of one file might affect the type-checking of another file, correct? Thus, I set the entry to `mypy .` and set `always_run: True`.

However, I am confused whether I should also set `pass_filenames: False`. Does `pass_filenames: False` disable any of the multithreading benefits of using this framework? Or are those benefits already disabled because I am explicitly using `mypy .`?

Similarly for pytest, does `pass_filenames: False` have any impact on the multithreading? It seems that all the tests in verbose mode are aggregated at the end either way, so I can't tell the difference.

I took a quick glance at the code, and if passing filenames truly has no multithreading benefits, then I should set `pass_filenames: False` to avoid shuffling the filenames extra times...

**Comment by asottile** [comment]
I would recommend against doing what you're suggesting for `mypy` -- [use `--all-files` in CI](https://pre-commit.com/#usage-in-continuous-integration), but keep it fast locally (running only on the changed files).  The default configuration is set up for the best practice that does this already.

It's a trade off, but you'll be much happier not waiting forever always for the rare case where you accidentally touch a file that doesn't affect everything else.

___

That said, if you want to continue on into not-suggested territory and turn off many of the features you can!

since I'm not sure of your configuration (you didn't share it) I'm guessing it is this:

```yaml
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: ...
    -   id: mypy
        entry: mypy .
        always_run: true
```

[this will run](https://pre-commit.com/#arguments-pattern-in-hooks):

```
mypy . filename1.py filename2.py filename3.py
# and if that command is too long
mypy . filename99.py filename100.py
```

(probably not what you want! and doing a bunch of unnecessary work linting every file at least two times)

so if you're going to do what you're going to do, you want `pass_filenames: false`


note that the only thing that controls multiprocessing is the [`require_serial`](https://pre-commit.com/#hooks-require_serial) setting, and mypy [already sets this to true](https://github.com/pre-commit/mirrors-mypy/blob/f3bfcb5479b4fa73b3fbb95a6390420575f20b51/.pre-commit-hooks.yaml#L7) because mypy is not parallel safe and even if it was it would do a lot of duplicated slow work many times

__

I would also recommend against running `pytest` as part of your hooks, it's going to be slow and difficult to configure -- you can read more about my recommendations [here](https://github.com/pre-commit/pre-commit-hooks/issues/291#issuecomment-394167917) -- that said if your thing is dead simple you might be able to still use pytest -- for example [this](https://github.com/pre-commit/pygrep-hooks/blob/eae6397e4c259ed3d057511f6dd5330b92867e62/.pre-commit-config.yaml#L47-L53)
