### ISSUE TITLE
autoupdate: determine redirects and tke them in

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [pre-commit/pre-commit#1640]
while updating a old repo i work with, i noted that it still used the ambv link to black instead of the one in the psf organization
(works thanks to redirect)

i wonder if there is a inexpensive way for pre-commit to auto-follow on autoupdate to use the new url of the hook

**Comment by asottile** [comment]
I forget where (might've been discord? might've been an issue?) but we discussed this and found it's not possible

the git protocol doesn't expose this and writing something github-specific doesn't seem generically useful or maintainable

that said, I think this is something pre-commit.ci will handle in the auto-updater since it's in its best interest to try and dedupe things for cache performance
