### ISSUE TITLE
prettier fails to install

### ISSUE THREAD

**Issue by WhyNotHugo** [pre-commit/pre-commit#1670]
I'm using prettier's hook, and it's failing to run all of a sudden:

```
❯ pre-commit run prettier
[WARNING] Unstaged files detected.
[INFO] Stashing unstaged files to /home/hugo/.cache/pre-commit/patch1603988462.
[INFO] Installing environment for https://github.com/prettier/prettier.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Restored changes from /home/hugo/.cache/pre-commit/patch1603988462.
An unexpected error has occurred: CalledProcessError: command: ('/home/hugo/.cache/pre-commit/repow3gefvtb/node_env-system/bin/node', '/usr/bin/npm', 'install', '--dev', '--prod', '--ignore-prepublish', '--no-progress', '--no-save')
return code: 1
expected return code: 0
stdout: (none)
stderr:
    npm WARN install Usage of the `--dev` option is deprecated. Use `--include=dev` instead.
    npm ERR! code ERESOLVE
    npm ERR! ERESOLVE unable to resolve dependency tree
    npm ERR!
    npm ERR! While resolving: prettier@2.1.2
    npm ERR! Found: remark-parse@8.0.3
    npm ERR! node_modules/remark-parse
    npm ERR!   remark-parse@"8.0.3" from the root project
    npm ERR!
    npm ERR! Could not resolve dependency:
    npm ERR! peer remark-parse@"^3.0.0 || ^4.0.0 || ^5.0.0 || ^6.0.0" from remark-math@1.0.6
    npm ERR! node_modules/remark-math
    npm ERR!   remark-math@"1.0.6" from the root project
    npm ERR!
    npm ERR! Fix the upstream dependency conflict, or retry
    npm ERR! this command with --force, or --legacy-peer-deps
    npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
    npm ERR!
    npm ERR! See /home/hugo/.npm/eresolve-report.txt for a full report.

    npm ERR! A complete log of this run can be found in:
    npm ERR!     /home/hugo/.npm/_logs/2020-10-29T16_21_07_309Z-debug.log

Check the log at /home/hugo/.cache/pre-commit/pre-commit.log
```

- I was on pre-commit 2.6.0, but updating to 2.8.1 changed nothing.
- My hooks are pinned, so I'm running everything on the same version.

Any hints here? I can't quite figure out what's changed, or where.

**Comment by asottile** [comment]
there's a duplicate somwhere but I'm having trouble finding what repository it was in, I thought it was here but it might be one of the prettier repos now that I think about it

node 15 (and new npm) were released which breaks the dependencies pinned (and conflicting) in prettier 2.1.1's `package.json` (which I assume is the one you're using since I can't see the configuration?)

there's a couple ways around this:
- I believe prettier 2.1.2 doesn't have this problem
- prettier is currently migrating from prettier/prettier to prettier/pre-commit -- maybe try this other repository instead?
- you could pick a particular node version using `language_version`
- you could globally install node and then the `language_version` will default to `system`

**Comment by asottile** [comment]
found it!  https://github.com/prettier/prettier/issues/9459

**Comment by WhyNotHugo** [comment]
Ah, thanks! I never would have guessed that was the issue.

Moved to using `https://github.com/prettier/pre-commit`, and that fixed it for me.
