### ISSUE TITLE
Test for executables fails on Windows

### ISSUE THREAD

**Issue by JohnLBevan** [pre-commit/pre-commit#1673]
When running pre-commit on a Windows device, the pre-commit hook `check_executables_have_shebangs` flags up a number of non-executable (YAML) files as failing.  Running Git Bash shows these files in white rather than green (i.e. showing that they're not considered as executable).  I've raised this issue here rather than under the pre-commit-hooks repo as I believe the logic to detect what's considered executable is part of the generic pre-commit library / that's just called by the relevant hooks.  
Hopefully this is the correct place?  Apologies if not.

![image](https://user-images.githubusercontent.com/1840140/97699172-9c57f900-1aa1-11eb-9fbf-e523b65f0cea.png)

**Comment by asottile** [comment]
this is not the correct place (pre-commit/pre-commit: the framework) -- you're looking for (pre-commit/pre-commit-hooks: the repository where those particular tools come from), but I'll save you the jump and tell you to upgrade (easiest is via `pre-commit autoupdate`) since you're using an old version of pre-commit-hooks and this already got fixed :)

in the future, don't post screenshots of plain text -- it's text for a reason!  it's especially problematic because (1) it's inaccessible: the user can't view it in their own contrast / font settings (2) it's unsearchable: a future user cannot find this issue based on the important text in the error messages
