### ISSUE TITLE
python hooks via pypi

### ISSUE THREAD

**Issue by florianschanda** [pre-commit/pre-commit#1705]
Hi!

I've come across your very nice project via a PR on one of my own projects. Seems like a really good idea to simplify the world of hooks! :)

A user would like to have miss_hit running as a pre-commit hook; and the way you appear deal with python hooks looks super strange to me. So, most likely, I missed something in your documentation; if so please educate me; but if not please consider this a feature request :)

I have a very tricky packaging process for PyPI, and having a setup.py in the repo root for miss_hit is just not practical. As far as I understand a pre-commit python hook is:
1. downloaded by your system
1. build and installed in some local dir
1. run

But there are some issues that I don't understand:
* for projects that do not have a stable master, you need to bake in a specific revision?
* is there no way to just fetch a pypi package and run an entry-point inside?

That way, users also get the latest stable version by default.

**Comment by MarcoGorelli** [comment]
Hi @florianschanda 

I'm not a maintainer, but hopefully I can help answer some of your questions.

>  for projects that do not have a stable master, you need to bake in a specific revision?

Users need to specify a revision (a commit or a tag) - for example:
```
-   repo: https://github.com/asottile/pyupgrade
    rev: v2.7.4
```
or
```
-   repo: https://github.com/asottile/pyupgrade
    rev: 59b49e77e418526be489c303b87fa2e19342fe6a
```
are both valid.

If they specify the latest tag, then they can use `pre-commit autoupdate` to update to the latest available tags.

> is there no way to just fetch a pypi package and run an entry-point inside?

You could make a local repo and then specify the pypi package in `additional_dependencies`, e.g. something like
```
repos:
  - repo: local
    hooks:
      - id: mh_metric
        name: mh_metric
        language: python
        files: \.m$
        entry: python -m miss_hit_core.mh_metric
        additional_dependencies: [miss_hit]
```

My understanding is that this will run `python -m miss_hit_core.mh_metric <file1.m> <file2.m> ... <filen.m>` in a virtualenv which has `miss_hit` installed in it

**Comment by asottile** [comment]
there were a couple decisions for the distribution mechanism for pre-commit via git instead of via pypi:

- pre-commit (while implemented in python) is not a python-specific tool
- pre-commit supports installing tools from many programming languages
- additional metadata is necessary to run tools (notably the language they are, what files they apply to, additional arguments needed, additional dependencies needed, and some other characteristics of how they run)
- pre-commit aims for repeatability: requiring a version for each tool
- this repeatability also allows things to be cached and fast

that said, there is an escape hatch as @MarcoGorelli points out: `local` hooks.  though these put the burden of the "correct" metadata all on the user and cannot be updated automatically as a tool evolves since the metadata is duplicated in every consuming repository

your repository doesn't necessarily need a setup.py, it just needs to be pip installable (whether that's pyproject.toml or setuptools-based).  roughly equivalent to how someone might try and use a development version of your library via `pip install git+https://github.com/.../...@...`

**Comment by florianschanda** [comment]
Hi, thank you all for your answers. I've resolved via a config file suggestion very similar to @MarcoGorelli
