### ISSUE TITLE
Option to select the number of parallel processes

### ISSUE THREAD

**Issue by AntoinePrv** [pre-commit/pre-commit#1710]
I believe an option to select the number of parallel processes used to run the hooks would be useful.

I have a memory intensive hook that creates out of memory errors when run in CI. To mitigate this, I added `require_serial: true` for this hook my `.pre-commit-config.yaml`.
However this has two limitations:
- I can only use one process or all, but no in-between;
- I am forcing everyone (including myself) to use a single process locally.

Is this something that would make sense adding to pre-commit? Or is there an alternative I am missing here?

**Comment by asottile** [comment]
here's the current logic: https://github.com/pre-commit/pre-commit/blob/6e37f197b070e6d4ec2a59bd12d94ed7dd1f5374/pre_commit/languages/helpers.py#L102-L113

I don't really want to extend this further, it sounds like the actual bug is the memory-intensive hook

**Comment by AntoinePrv** [comment]
Ok, thanks. Looks like at least I can use `PRE_COMMIT_NO_CONCURRENCY` to avoid hard coding it.

> it sounds like the actual bug is the memory-intensive hook

Actually it's a mix between the tool itself (clang-tidy) and the CI provider that kills on OOM, but either way there doesn't seem to be an easy solution.

**Comment by fsouza** [comment]
@asottile would you be willing to revisit this? We're running into some scenarios where sched_affinity is not returning the right number of CPUs, and we should be able to inject the right number of CPUs with an environment variable. For now we're running a patched version of pre-commit, but I wonder if it would make sense to have a knob in pre-commit to simply set the target_concurrency (either via a flag or environment variable).

(also I wasn't sure whether to open a new issue or comment here, so went with the one that should generate less toil for you, please let me know if you prefer another issue)

**Comment by asottile** [comment]
I don't want to add a knob (especially because it will be misused).  I'm more interested in your situation and why the os is lying to you -- should be easier to fix that

**Comment by elventear** [comment]
@asottile when running in kubernetes what `multiprocessing.cpu_count()` returns and what the container can use can be verey different things. E.g. running in a 32 CPU node in an environment that is supposed to only use 4. Usually memory and concurrency are proportional so even if the scheduler can throttle down actual CPU usage, you can end up in OOM situations easily because too many tasks are started at the same time.

**Comment by asottile** [comment]
we don't use that any more to determine cpu count so I'm not sure what
you're 6 point is

**Comment by elventear** [comment]
@asottile My apologies. I did remove my comment as I noticed that I was looking at something outdated. Alas, you still got the email.

**Comment by gpshead** [comment]
## Workaround

Python 3.13 adds the [`PYTHON_CPU_COUNT` environment variable support](https://docs.python.org/3/whatsnew/3.13.html#os).  **Suggestion**: Use a 3.13+ pyenv to run pre-commit and use that.

Without that, monkeypatching pre-commit or Python stdlib itself would be required.  It _would_ have been friendlier if pre-commit just supported a --jobs flag on `pre-commit run` in the first place like other software always has w.r.t. parallelism. 🤷🏾 

## Why configurable parallelism is necessary

https://github.com/pre-commit/pre-commit/blob/d2b61d0ef2cc6323246451615f1f9fe506db976c/pre_commit/xargs.py#L26-L38

Is still inadequate for real situations.  `os.sched_getaffinity(0)` only helps if you are using cgroup hard limits on cpus.  in environments where you happily allow borrowing of excess unscheduled cpu cores it'll return the number of cpus on the system rather than the number your container is supposed to restrict itself to.

The real underlying problem behind all of this is often not so much cpu, it is total ram consumed.  it is easy to have systems with hundreds of cpus.  but spawning that many processes at once leads to OOMs because our container has a memory limit which we _do_ enforce strictly to stay within even if we allow consuming excess cpu cores by not using hard limits and having the cpu scheduler limit how much we get via priorities vs others.  _(this is a common cluster configuration in my experiences)_

why so much ram? static analyzers like type checkers consume large amounts of ram as they each load a graph representing a good chunk of the entire codebase regardless of which files they're passed as they are transitive in nature.

long term reason: The language pre-commit is implemented in should be an implementation detail and not necessary for users to know. Rewrite it in Rust or Golang or Fig in the future and the above workaround would no longer work.

**Comment by asottile** [comment]
type checkers typically use `require_serial: true` so your rationale seems dubious at best

**Comment by tburt-nv** [comment]
Hi @asottile, `sched_getaffinity` and `multiprocessing.cpu_count` might work great in many environments, but it doesn't work great in every environment. For example, some machines have multiple active users/developers. The primary issue in these contexts is not thread safety, but out of memory errors caused by resource contention.

Pre-commit has great isolation features out of the box that makes it easy to use in systems with multiple users. Adding this option will help make it even easier for those users to take advantage of limited concurrency, without having to completely disable concurrency or learn how to set up their own cgroups.

Please reconsider rejecting this minor request for enhancement. To mitigate concerns about misuse, would a warning in the documentation be sufficient? Even leaving the feature/knob undocumented could allow advanced users to customize the concurrency.

> type checkers typically use require_serial: true so your rationale seems dubious at best

Some project may want to implement their own memory-intensive checks that use a stable amount of memory per process. Manually controlling the number of concurrent processes seems reasonable to me in these cases. What do you think?

**Comment by asottile** [comment]
use cgroups to properly isolate your users and resources then

I'm not going to add this complexity to pre-commit.
