### ISSUE TITLE
init-templatedir installing hooks to wrong directory

### ISSUE THREAD

**Issue by chronoB** [pre-commit/pre-commit#1720]
I was trying to use the init-templatedir functionality of pre-commit and ran into a weird problem:

Using Windows 10, pre-commit 2.9.2, git version 2.29.2.windows.1

I followed the example on the pre-commit.com website and used:
```
git config --global init.templateDir ~/.git-template
pre-commit init-templatedir ~/.git-template
```
![grafik](https://user-images.githubusercontent.com/11942682/100527714-36ac7900-31d5-11eb-8312-ab5dc966e7ea.png)

It wants me to be in a git repository (I thought you prevented this with da80cc6479154c0a0a6096d183f9d1d72aae556b).
So i switched to a git repository and rerun 
```
pre-commit init-templatedir ~/.git-template
```
![grafik](https://user-images.githubusercontent.com/11942682/100527744-a7ec2c00-31d5-11eb-8b45-4bcc4093dd12.png)

the hooks aren't installed in the stated directory.
Based on the warnings it looks like pre-commit isn't resolving the ~ correctly, or did I miss sth.?

```
git config --get init.templateDir 
```
returns ~/.git-template

![grafik](https://user-images.githubusercontent.com/11942682/100527765-e41f8c80-31d5-11eb-95d6-9fc95aa96841.png)

**Comment by asottile** [comment]
Ahah, so the first part of this is that the cygwin check relies on being in a git repo and it is only run on windows -- that's why it only was failing on windows and why I didn't notice the regression there

As for the other components here, `~` is a special shell expansion on posix -- on windows you'll use `%HOMEPATH%\.git-template` instead (this probably is worth a documentation update -- the docs live at [https://github.com/pre-commit/pre-commit.com](pre-commit/pre-commit.com) if you'd like to contribute to them!).

If we try with `%HOMEPATH%` I get this output:

```
(venv) C:\Users\Anthony\workspace\wat>pre-commit init-templatedir %HOMEPATH%\.git-template
pre-commit installed at \Users\Anthony\.git-template\hooks\pre-commit
[WARNING] `init.templateDir` not set to the target directory
[WARNING] maybe `git config --global init.templateDir C:\Users\Anthony\.git-template`?

(venv) C:\Users\Anthony\workspace\wat>git config --global init.templateDir %HOMEPATH%\.git-template

(venv) C:\Users\Anthony\workspace\wat>pre-commit init-templatedir %HOMEPATH%\.git-template
pre-commit installed at \Users\Anthony\.git-template\hooks\pre-commit
```
