### ISSUE TITLE
Add mirror for stylelint

### ISSUE THREAD

**Issue by ogomozov-godaddy** [pre-commit/pre-commit#1768]
Eslint is standard linter for Javascript. However, there is no yet leader for CSS
So far only scss-lint has mirror in pre-commit hooks
https://github.com/pre-commit/mirrors-scss-lint
However, it's biggest issue is not able to "autofix" simple errors like other linters do and is expected by many users
This issue is not going to be fixed any time
https://github.com/sds/scss-lint/issues/984

It's biggest rival is stylelint. It has more features: supports many syntax besides SCSS, more rules, more config features, has larger community and contribution team. But most important - it allows autofix
https://stylelint.io/

Please, add mirror for stylelint

**Comment by asottile** [comment]
It would be preferable to suggest a configuration to their repository (essentially add the `.pre-commit-hooks.yaml` file there) -- please pursue that first.

**Comment by asottile** [comment]
note that you can always add a `repo: local` hook which uses `stylelint` as an `additional_dependencies: [...]` until official support lands

**Comment by thibaudcolas** [comment]
👋  I wanted to follow up on this as we’re discussing the future of stylelint’s pre-commit hooks at [stylelint/stylelint#5373](https://github.com/stylelint/stylelint/issues/5373).

- It looks like the preference there would be to maintain the hook as a mirror rather than inside the main repository
- Stylelint maintainers also don’t want to have more repositories under the `stylelint` organisation on GitHub

I’ve made <https://github.com/thibaudcolas/mirrors-stylelint> as a trial, based on `mirrors-prettier`, but matching the configuration of [`awebdeveloper/pre-commit-stylelint`](https://github.com/awebdeveloper/pre-commit-stylelint), as that’s what current users would be migrating from (installing it is a pain but afterwards it works pretty well as-is). 

From what I understand there are two options:

1. We move the repository I made to the `pre-commit` organisation, like [mirrors-scss-lint](https://github.com/pre-commit/mirrors-scss-lint), and a lot of other Node-based linters. Then stylelint updates their docs to point at this "official" mirror.
2. We keep it under my account, and I’ll do my best to keep it maintained like other mirrors anyway. Then stylelint updates their docs to point at this unofficial-but-endorsed mirror.

@asottile what do you think?

**Comment by asottile** [comment]
the mirror repositories are suboptimal workarounds -- the ideal state is adding the one small metadata file to the source repository

**Comment by thibaudcolas** [comment]
I can see that in some respect, but from what I could piece together between https://github.com/prettier/prettier/issues/8925#issue-674202527 and looking at pre-commit’s [Node environment installation steps](https://github.com/pre-commit/pre-commit/blob/84372e0edc7f5ac08361a10bcd312bc80dd20960/pre_commit/languages/node.py#L104-L114), it seems installation speed is also a factor that makes a mirror more compelling as things stand currently.

Anyway, in the case of stylelint I have a feeling there’s already consensus that a mirror is the way to go at least for the time being.

**Comment by asottile** [comment]
again it's not about size or speed, it's about the user experience. mirror repositories are far worse due to them being essentially a hack via additional_dependencies which are a constant source of confusion. they also redirect support away from those that can properly handle their problems

but if you want to do the wrong thing by all means go ahead, I'm just requesting you do it the right way for the users

**Comment by thibaudcolas** [comment]
In case anyone researches this in the future  – I wrote a quick report on how the mirror has been working over the last year and a half: https://github.com/thibaudcolas/pre-commit-stylelint/discussions/1. I’m planning to introduce Stylelint on a major project so had to take a look at this again.

**Comment by asottile** [comment]
your experience seems anecdotal fwiw.  the prettier mirror issue tracker has gotten so bad I've had to lock it multiple times
