### ISSUE TITLE
pre-commit doesn't keep current project/virtualenv in sys.path

### ISSUE THREAD

**Issue by guykisel** [pre-commit/pre-commit#178]
I'm trying to get Prospector ( https://github.com/landscapeio/prospector ) to run as a pre-commit hook. By default, Prospector will run pylint, including pylint's import checker.

I was getting confused, because I kept getting output that looks like:

```
test_mailing_lists (<projectname>/tests/services/platform/email/test_mailing_lists.py):
    L8:0 None: pylint - F0401
    Unable to import '<projectname>.services.platform.email.mailing_lists'
```

Even though directly running Prospector in the project (as opposed to via pre-commit) doesn't raise these errors.

When I print `sys.path` from inside a Python script run by pre-commit as a hook, I get:

```
['/Users/gkisel/.pre-commit/repodfiUn9/py_env/bin',
 '/Users/gkisel/.pre-commit/repodfiUn9/py_env/lib/python27.zip',
 '/Users/gkisel/.pre-commit/repodfiUn9/py_env/lib/python2.7',
 '/Users/gkisel/.pre-commit/repodfiUn9/py_env/lib/python2.7/plat-darwin',
 '/Users/gkisel/.pre-commit/repodfiUn9/py_env/lib/python2.7/plat-mac',
 '/Users/gkisel/.pre-commit/repodfiUn9/py_env/lib/python2.7/plat-mac/lib-scriptpackages',
 '/Users/gkisel/.pre-commit/repodfiUn9/py_env/Extras/lib/python',
 '/Users/gkisel/.pre-commit/repodfiUn9/py_env/lib/python2.7/lib-tk',
 '/Users/gkisel/.pre-commit/repodfiUn9/py_env/lib/python2.7/lib-old',
 '/Users/gkisel/.pre-commit/repodfiUn9/py_env/lib/python2.7/lib-dynload',
 '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7',
 '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-darwin',
 '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk',
 '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac',
 '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac/lib-scriptpackages',
 '/Users/gkisel/.pre-commit/repodfiUn9/py_env/lib/python2.7/site-packages',
 '/Users/gkisel/.pre-commit/repodfiUn9/py_env/lib/python2.7/site-packages/astroid/brain']
```

Note that this doesn't appear to include my project directory or my virtualenv path. I think this is why pylint (within Prospector) is unable to successfully run those import statements.

Is this behavior intentional? Am I doing something incorrectly? Is there a way I can get pre-commit to preserve my `sys.path` when running Python hooks?

For reference, see https://github.com/guykisel/prospector-mirror

**Comment by lokesh1729** [comment]
> In hooks.yaml you can create a hook which is of the langauge `system` instead of `python`. This has the unfortunate side-effect of depending on what is installed at the system level and doesn't take advantage of any of the containerization, etc. But it'll execute using the environment (including pythonpath, etc.) of the shell at the time of `git commit` (instead of executing in an isolated virtualenvironment).
> 
> An example file might look like this:
> 
> ```
> # hooks.yaml
> -   id: my-id
>     name: My Hook name
>     description: A description for my hook
>     language: system
>     entry: pylint
> ```

@asottile 
I have configured pylint as a system hook, but it wasn't taking the current shell's python virtualenv...

this is the config I have

```
-   repo: local
    hooks:
    - id: pylint
      name: pylint
      language: system
      types: [python]
      entry: "python -m pylint --rcfile=.pylintrc --load-plugins=pylint_django --load-plugins=pylint_django.checkers.db_performance"
-   repo: local
    hooks:
    - id: hey
      name: hey
      language: system
      entry: "which python"
-   repo: local
    hooks:
    - id: hello
      name: hello
      language: system
      entry: "which pylint"
```

when I run it, I see the path of `python` and `pylint` like this

> hey......................................................................Failed
> hookid: hey
>
> /Users/slokesh/.pyenv/versions/3.6.5/bin/python
>
> hello....................................................................Failed
> hookid: hello
>
> /Users/slokesh/.pyenv/versions/3.6.5/bin/pylint

But, when I see `python` and `pylint` paths, they are in virtual env...

![image](https://user-images.githubusercontent.com/13495829/59553281-9b0f5480-8fb0-11e9-8e4e-09183a3c2663.png)

**Comment by asottile** [comment]
Can you `hash -r` and then try your `which` commands again?

**Comment by lokesh1729** [comment]
yes... `hash -r` does the trick... but I am wondered what's the trick??? what is the cause of the issue??/ I actually have installed `pre-commit` hooks before and then `clean` them and then tried installing again... is that what it's causing... can you explain what's the logic behind ???

**Comment by asottile** [comment]
your `which` command was misleading you -- the shell implements a "cache" of binaries that it knows from `PATH` lookup -- whereas `pre-commit` computes the executable location from the "true" `PATH`

**Comment by lokesh1729** [comment]
the reason I added "which" is because `pylint` is failing to detect `django` in my current virtual environment... if `pre-commit` computes the location, then why does it fail to import `django` ??

**Comment by asottile** [comment]
right -- I was mostly explaining why in your screenshot above you see a different `which` result inside / outside of `pre-commit`.  because the `which`s outside are using your shell's `hash` cache despite not actually being available.

For `language: system` you should be able to run the same command in and outside of pre-commit and receive the same results -- if you can show that not happening then there's a bug (though a report that involves `which` or shell builtins should run `hash -r` before invoking those commands).  Alternatively you can use `python3 -c 'import shutil; print(shutil.which("python"))'` etc.

___

an aside, one thing I noticed about the screenshot above is the `which` hooks show up as `Failed` -- however that seems impossible since which produced a result and exited zero -- was your configuration something different from that?

**Comment by lokesh1729** [comment]
@asottile  keeping `which` aside, the main purpose to put them is to debug `pylint` failing to import django. my main concern is `pylint` not the `which` commands.  so, when I did `hash -r` not only `which` command is showing the correct path but also previous `pylint` errors also gone, now it's able to import `django` from my virtual environment. can you tell me one thing, I am using `pyenv` to manage my python versions. since `pyenv` manipulates `PATH` variable by appending it's `shims` path in the front, does it affecting `pylint` path ???

**Comment by asottile** [comment]
`pyenv` itself shouldn't matter, but I imagine the hash cache (while in your shell) also was causing you to use the `pylint` executable you didn't expect as well?

**Comment by lokesh1729** [comment]
I didn't try with my shell before clearing the `hash`, so should I put a `hash -r` before the command?? is that needed for the `system` commands ???

**Comment by asottile** [comment]
the hash cache only affects the shell and has nothing to do with pre-commit here, I'd suggest reading the manual for your particular shell (for instance [bash](https://www.gnu.org/software/bash/manual/html_node/Bourne-Shell-Builtins.html) or [zsh](http://zsh.sourceforge.net/Doc/Release/Shell-Builtin-Commands.html)) describing the shell builtins and how they function -- the shell is a program like any other and the hash cache is stored in that program's memory.  pre-commit does not have access to that.

**Comment by lokesh1729** [comment]
@asottile I have gone through `hash`. Agreed to your points... So, it is good to use `hash -r` command before invoking `pylint`?

**Comment by asottile** [comment]
there's no point to doing that in `pre-commit`'s configuration -- I was only suggesting you try that in your shell to establish an amount of sanity / correct expectations for what pre-commit is going to do (while eliminating the cache invalidation problem of your shell)

**Comment by miry** [comment]
Just in case:

I had next hook:

```yaml
  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: poetry run pytest --
        language: python
        types: [python]
        files: ^tests\/.*test_.*\.py$
        pass_filenames: false  # or use with: require_serial
```

I use `poetry`. And on each changes of tests, it used different python.

Base on comment @asottile , I changed  `language: python` to `language: system` and everything started works.

**Comment by scop** [comment]
Another tool that is affected by this problem is mypy, it really needs stuff from the project's venv to work properly unless one pretty much completely ignores errors resulting from imports.

I think the `system` workaround isn't really applicable for cases where for example a git GUI tool (such as GitHub Desktop) is launched and stuff committed to a pre-commit enabled working dir; there's likely no opportunity to activate the project venv there.

Maybe a `script` approach that would activate the venv would work, dunno. But a problem there is that the way people use venvs differ; some prefer plain python -m venvs, others pyenv virtualenvs, the dirs where the venvs are set up vary, so the script would not be able to activate the venv properly in all cases, and forcing people to use virtualenvs some specific way would be kind of meh.

So it would be great if pre-commit would offer some more assistance in coping with these scenarios. Don't know what exactly would that be. Maybe e.g. some option that would "record" the currently active virtualenv settings at hook install time and use them later to construct the same environment when running the installed hook, dunno.
