### ISSUE TITLE
"Pass directories" option

### ISSUE THREAD

**Issue by jwilner** [pre-commit/pre-commit#1784]
Hi! Thanks for a great tool.

Currently, support for linters in languages which have directory-based "compilation units" is problematic. From personal experience, I'm talking about Go and Terraform.

Specifically, `pre-commit` defaults to passing filenames. In languages like Go and Terraform, linters often make a "best effort" if you pass a filename -- linting the file, but not pulling in the whole directory. Depending on the linter (and the file), this can produce undesirable results. For example, "unused symbol" analysis often reports false positives because, sure, the symbol is unused in the file, but not in the broader directory.

I have experienced this exact issue with `golangci-lint` and `tflint`. I've gotten around it by writing a bash wrapper which uniqifies the dirs of the input files and then passes those directories.

I think this would be a useful addition to pre-commit proper -- a flag like `pass_directories`. If this makes sense to you, I can put together a PR quickly.

**Comment by asottile** [comment]
yeah some linters are poorly formed like you describe

I don't think it makes sense to increase complexity here to support bad linters -- they should ideally operate fine on single files

it's less of a question of "could pre-commit do this" and rather "should pre-commit do this" -- the problem and the reason I don't want to support this is because it forces the user into a slow-performance realm (which in the end ends up being blamed on the framework instead of the tool or the particular configuration).  that is, the framework is intentionally designed around _filenames_ and when you get into uniquifying for directories you're necessarily going to lint way more than is intended.

the other problem with the proposal is there's not a single way one could interpret "directories" -- does a/b.t a/b/c.t uniquify to `a`? to `a` and `a/b`? to `.`? it's hard to say.

I'd suggest you encourage tools to improve their status quo rather than supporting something that can't possibly be done nicely


this has been discussed in the past, there's a few threads on it but I'm a little too busy at the moment to find those threads for you

**Comment by killthekitten** [comment]
Could using the "bad" linter hooks be resolved with `pass_filenames: false`? Then pre-commit won't make any assumptions over which files should be linted, and the linter would fall back to using its own config file.

**Comment by asottile** [comment]
yes you could, the caveats above apply (notably you'll do more work than necessary, you won't have the same merge conflict features, etc. etc.)

here's an example running a tool called "foo" on "sub/dir"

```yaml
-   repo: local
    hooks:
    -   id: foo
        name: foo
        entry: foo sub/dir
        files: ^sub/dir/
        pass_filenames: false
        # ... (language, additional_dependencies, types, etc.)
```
