### ISSUE TITLE
passing key / credentials when pulling from a private repo, seems to fail when they are not included or manually entered.

### ISSUE THREAD

**Issue by nathan9120** [pre-commit/pre-commit#1807]
hi,

i have written some custom scripts to run as pre commit actions. when i add this as config with https:// it prompts for a username and password to login. trying with the git:// protocol it fails. 

```
- repo: https://<private gitlab repo>/XXXX/validation
  rev: 0.1.2
  hooks:
    - id: terraform12_tflint
```

After putting in credentials this works.

however trying to use the git protocol i get this error:

### version information

```
pre-commit version: 2.10.1
sys.version:
    3.9.1 (default, Feb 17 2021, 15:18:42) 
    [Clang 12.0.0 (clang-1200.0.31.1)]
sys.executable: /Users/nathan.spence/brew/Cellar/pre-commit/2.10.1/libexec/bin/python3
os.name: posix
sys.platform: darwin
```

### error information

```
An unexpected error has occurred: CalledProcessError: command: ('/Library/Developer/CommandLineTools/usr/libexec/git-core/git', 'fetch', 'origin', '--tags')
return code: 128
expected return code: 0
stdout: (none)
stderr:
    fatal: read error: Connection reset by peer
    
```

**Comment by asottile** [comment]
first off, you've created this on the wrong project, pre-commit/pre-commit-hooks is a bunch of hook executables and is not the framework

as to your actual problem, may places **block** the `git://` protocol because it is inherently unsafe (it is unencrypted) -- it's likely you're just hitting that being blocked

if you run `git clone git://...` in the same way you should see exactly the same error

if I was brave enough, I'd have pre-commit **block** `git://` and `http://`, but I don't really want to deal with the fallout of users intentionally picking insecure protocols and then angering over my decision to make the tool more secure

I'd recommend using ssh urls if anything as those won't require you to place credentials in the clone url
