### ISSUE TITLE
View the list of files checked by the hooks

### ISSUE THREAD

**Issue by revolter** [pre-commit/pre-commit#1893]
Is it possible to view the list of all the files that are checked by all the hooks defined in the config file?

**Comment by asottile** [comment]
`pre-commit` sources its file list from [a few different ways](https://github.com/pre-commit/pre-commit/blob/7f13fa5d5fe41b4f692f2de9d7af53cae364522e/pre_commit/commands/run.py#L246-L261) depending on how it is being run

you can inspect which files would be passed to an individual hook by utilizing the [identity](https://pre-commit.com/#meta-identity) meta-hook

a less-portable way to do the same as identity is to set `entry: echo` + `verbose: true` temporarily

**Comment by revolter** [comment]
It's not clear for me how the `identity` hook could be used with another hook. And, for some reason, `entry: echo` + `verbose: true` doesn't work for me.

**Comment by asottile** [comment]
to use`identity`, copy the `files`, `exclude`, `types`, `exclude_types`, `types_or`

**Comment by asottile** [comment]
maybe if you share your configuration and what you're seeing I can better assist ?

**Comment by revolter** [comment]
I can't share it. Basically, I have a private hook, which I added multiple times with different regexes for the `files` parameter. And I recently noticed that some regexes were incorrect, and wanted to find out exactly how many files were checked when using `pre-commit run --all-files` before the fix, and how many files after the fix, to know for sure that I applied the correct modifications to the regexes.

**Comment by ehontoria** [comment]
Hi there, I'm also running into this issue where I would need the full list of the files that need to be checked. I'm writing a hook that checks whether a source _and_ compiled file are edited (one relies on the other, so either both of them should be edited or neither should). It ends up failing currently since the files to check are chunked up  for python executions (files 1-4 on first run, files 5-8 on second etc.).

Would you mind giving an example where the `identity` meta hook would allow me to check that full list of files for the hook that way even if it runs multiple times it would still have the same list of edited files each time (all files 1-8 or whatever)?

**Comment by asottile** [comment]
relying on all the filenames to be passed in one invocation is a flawed design so you might want to reconsider that -- there are length limits to commandlines so you can't always fit every file path into a single call -- I'd recommend rearchitecting how your hook works to not care how many times it is called (you can use [`require_serial`](https://pre-commit.com/#hooks-require_serial) to eliminate parallelism, this tends to mean more files are passed to the hook at once but it does not guarantee a single call (as that's impossible))

one idea would be inspecting the modified filenames yourself inside the hook (+`always_run: true`, `pass_filenames: false`, + calling `git diff --staged --name-only`)

**Comment by ehontoria** [comment]
Sounds good - I ended up implementing grabbing the file names to check myself as you suggested. Thank you!
