### ISSUE TITLE
way to set fail_fast to false when using `pre-commit run --all-files .` for script usage

### ISSUE THREAD

**Issue by drjasonharrison** [pre-commit/pre-commit#1910]
Is there a way to set `fail_falsel: false` when using `pre-commit run --all-files`?

I'm running a git merge from several repos into a mono-repo with a call to `pre-commit run --all-files` to clean up any thing that can be cleaned up automatically.

Right now I'm working around the fail_fast setting with:

```
mv .pre-commit-config.yaml .pre-commit-config.yaml.bak
grep --invert-match "fail_fast".pre-commit-config.yaml.bak > .pre-commit-config.yaml
pre-commit run --all-files
mv .pre-commit-config.yaml.bak .pre-commit-config.yaml
```

**Comment by asottile** [comment]
there is not, but I think you can leverage `--config` to do what you want

**Comment by drjasonharrison** [comment]
Ah, I see --commit in the documentation but not from the command line in the output from -h

**Comment by asottile** [comment]
hmmmm I see it in the help ?

```console
$ pre-commit run --help
usage: pre-commit run [-h] [--color {auto,always,never}] [-c CONFIG]
                      [--verbose] [--all-files | --files [FILES [FILES ...]]]
                      [--show-diff-on-failure]
                      [--hook-stage {commit,merge-commit,prepare-commit-msg,commit-msg,post-commit,manual,post-checkout,push}]
                      [--remote-branch REMOTE_BRANCH] [--from-ref FROM_REF]
                      [--to-ref TO_REF]
                      [--commit-msg-filename COMMIT_MSG_FILENAME]
                      [--remote-name REMOTE_NAME] [--remote-url REMOTE_URL]
                      [--checkout-type CHECKOUT_TYPE]
                      [hook]

positional arguments:
  hook                  A single hook-id to run

optional arguments:
  -h, --help            show this help message and exit
  --color {auto,always,never}
                        Whether to use color in output. Defaults to `auto`.
  -c CONFIG, --config CONFIG
                        Path to alternate config file
  --verbose, -v
  --all-files, -a       Run on all the files in the repo.
  --files [FILES [FILES ...]]
                        Specific filenames to run hooks on.
  --show-diff-on-failure
                        When hooks fail, run `git diff` directly afterward.
  --hook-stage {commit,merge-commit,prepare-commit-msg,commit-msg,post-commit,manual,post-checkout,push}
                        The stage during which the hook is fired. One of
                        commit, merge-commit, prepare-commit-msg, commit-msg,
                        post-commit, manual, post-checkout, push
  --remote-branch REMOTE_BRANCH
                        Remote branch ref used by `git push`.
  --from-ref FROM_REF, --source FROM_REF, -s FROM_REF
                        (for usage with `--from-ref`) -- this option
                        represents the original ref in a `from_ref...to_ref`
                        diff expression. For `pre-push` hooks, this represents
                        the branch you are pushing to. For `post-checkout`
                        hooks, this represents the branch that was previously
                        checked out.
  --to-ref TO_REF, --origin TO_REF, -o TO_REF
                        (for usage with `--to-ref`) -- this option represents
                        the destination ref in a `from_ref...to_ref` diff
                        expression. For `pre-push` hooks, this represents the
                        branch being pushed. For `post-checkout` hooks, this
                        represents the branch that is now checked out.
  --commit-msg-filename COMMIT_MSG_FILENAME
                        Filename to check when running during `commit-msg`
  --remote-name REMOTE_NAME
                        Remote name used by `git push`.
  --remote-url REMOTE_URL
                        Remote url used by `git push`.
  --checkout-type CHECKOUT_TYPE
                        Indicates whether the checkout was a branch checkout
                        (changing branches, flag=1) or a file checkout
                        (retrieving a file from the index, flag=0).
```

(it's right up at the top)

**Comment by drjasonharrison** [comment]
Ah, sometimes I forget to try -h after the command.

**Comment by asottile** [comment]
cheers!

**Comment by dbari** [comment]
@asottile sorry for commenting on an already closed issue, but I prefer it to opening a duplicate.

It would make some workflows easier if `fail_fast` could be set both in the config file as a default for the repo and on the command line to possibly override the value of the config file. I manage a repo that includes a `mypy` hook, which due to the code structure is quite slow. Users prefer to have quick feedback when one of the other 10 or so hooks fail on some detail without waiting 2-5 seconds for `mypy` to complete on each commit, especially those that create lots of fine-grained commits. On the other hand, sometimes a full list of errors is needed, which would be best solved by a `--fail-fast` cli option (or `--no-fail-fast` to temporarily disable it). It is especially annoying if using an IDE like VScode, where you only get feedback on a possible failure after `pre-commit` has completed.

Although it can be handled using an extra config file, is it something you just don't want to invest the time into, or something you don't see in `pre-commit` even if contributed by others?

**Comment by asottile** [comment]
your problem is so much of an edge case of an edge case and there's already two good existing solutions to do exactly what you want (either config or manual).  I'm not going to add a feature that I would never use and never recommend with a bunch of complexity that I'd have to carry forever

it's exhausting to have decisions constantly questioned like this.  please don't
