### ISSUE TITLE
Possible to view the exact command that pre-commit is running?

### ISSUE THREAD

**Issue by max-sixty** [pre-commit/pre-commit#1916]
Firstly thank you for the excellent library! I've deployed it on many projects and it's proved really helpful.

Currently a pre-commit hook is raising an error when running mypy. But when I run `mypy .` or even [`mypy --scripts-are-modules --ignore-missing-imports **/*.py`](https://github.com/pre-commit/mirrors-mypy/blob/v0.812/.pre-commit-hooks.yaml#L6), I don't get the error.

So I'm not guessing the command that pre-commit is running correctly. Is it possible to view the command that pre-commit is running, so I can understand why there's a difference between running mypy in pre-commit vs alone?

**Comment by asottile** [comment]
there's a lot of dupes, here's one at least: https://github.com/pre-commit/pre-commit/issues/1446#issuecomment-626368324 -- this is intentionally not exposed because of the implementation details leaked by showing the command (which causes users to muck with the virtualenvs and cause more un-actionable self-inflicted issues)

I think you should read the README of [mirrors-mypy](https://github.com/pre-commit/mirrors-mypy) -- it's short and addresses your question, in case you miss it:

> **pre-commit runs mypy from an isolated virtualenv (without your dependencies)**

**Comment by max-sixty** [comment]
Thanks. Sorry to miss that one.
