### ISSUE TITLE
[FR] Additional dependency pins?

### ISSUE THREAD

**Issue by webknjaz** [pre-commit/pre-commit#1963]
So there's one thing that's been bothering me for some time: the inability to have consistently reproducible linter envs.
When I add a hook for `flake8`, I normally also specify some plugins via `additional_dependencies` but then, if any of those plugins or their transitive deps change, there's a chance that the linters will suddenly start failing for no obvious reason when there's no changes to the project.
I don't like pinning those plugin versions because (1) there's no tooling to autobump them specifically and (2) even if the direct deps are pinned, the indirect ones aren't which assumes a level of fragility.
I suppose this could be solved with the `PIP_CONSTRAINTS` env var but it would be nice to have some mechanism that would translate into pre-commit running `pip install -r requirements.txt -c constraints.txt`.
Ideas?

**Comment by asottile** [comment]
you can already specify whatever pip options you want inside `additional_dependencies`

**Comment by webknjaz** [comment]
Really? Any examples? as in `'-c file.txt'`?

**Comment by asottile** [comment]
https://github.com/pre-commit/pre-commit/blob/68294256a18fcef126dc246d641c056c94123e5b/pre_commit/languages/python.py#L199

note that you won't be able to install from the repository under test as pre-commit never does that (due to cache intractability) -- and you also have caching issues if you point at (say) `/etc/constraints.txt` as that will not be invalidated when the contents change

**Comment by webknjaz** [comment]
> note that you won't be able to install from the repository under test

Why? That's usually exactly a typical use-case.

**Comment by asottile** [comment]
> 
> 
> > note that you won't be able to install from the repository under test
> 
> Why? That's usually exactly a typical use-case.

please search the issue tracker: https://github.com/pre-commit/pre-commit/issues?q=is%3Aissue+%22repository+under+test%22+is%3Aclosed+ -- it's an intractable problem

**Comment by webknjaz** [comment]
Oh, looks like my google-fu failed me (I suspected that it's been raised before and actually did the search but probably used the wrong keywords). I suppose you're referring to https://github.com/pre-commit/pre-commit/issues/730, right?

Do I understand correctly that to achieve what I want I need to rewrite the config to run flake8+plugins+pins via a local hook?

**Comment by asottile** [comment]
you don't _need_ a local hook -- it can be done with pycqa/flake8 directly (and that's recommended)

**Comment by webknjaz** [comment]
Could you post a full example? I don't understand how that's possible 🤷‍♂️

**Comment by asottile** [comment]
```yaml
    -   id: flake8
        additional_dependencies: [
            your==...,
            pins==...,
            here==...,
        ]
```

**Comment by webknjaz** [comment]
Oh, that is not what I want: I need the whole deptree pinned which shouldn't be a manual effort + it feels wrong to put tens of indirect deps in this config file.

**Comment by ssbarnea** [comment]
I have exactly the same problem. Having to maintain dependency locks inside the pre-commit lock does not make much sense and prevents us from using dependency management tools like pip-compile or dependabot.

I really soo no reason why we would not allow for someone to make use `-cconstraints.txt` as this would only control the dependencies better and not worse. Based on the error I am seeing I suspect that pre-commit does change current directory to something else than the current codebase. Still, we should have a way to refer to the project dir, something similar with `{toxinidir}` macro for example.

I do understand the worries around "cache intractability" but at the same time I realise that defending immutability of the cache does endup making use of pre-commit with pylint, mypy and to some extent maybe even flake8 unreliable, more unreliable than the old way of using tox to run them. At least tox v4 sorted the problem where it failed to update the virtualenv when deps/constraints changed. My guess is that the author wants to avoid running pip at all costs once an environment was created but the reality is that may not play well for the users. In fact most people that use additional_dependencies do not pin them. If they are lucky they may put put ranges but still this means that cache created at one point will not be the same as the cache created at another moment in time, so results will not be as deterministic as some would want them to be.

I think I was able to find a hack to force it to respect constraints file and find the path to it by calling it with `PIP_CONSTRAINT=$(pwd)/constraints.txt pre-commit run pylint` but that will not update the env when constraints file is updated.

Thus makes me believe the only option is to stop using pre-commit ability to manage virtualenvs and rely on tox for doing this, basically using tox as a wrapper for pre-commit and making use of system hooks. This would also fix other problems like autoupdate picking up undesirable pre-release tags (pylist being such an example).

**Comment by asottile** [comment]
@ssbarnea I don't appreciate you dogpiling on every single issue about this -- I've heard your opinion but you don't understand the technical parts of this and I've already requested you to stop

but I'm glad you brought up `tox` because it serves as a perfect example of why this isn't feasible

even a trivial run of tox adds 1.6s to the execution, an unacceptable startup time for pre-commit:

```
$ time tox4 -e wat
.pkg: get_requires_for_build_wheel> python /tmp/y/astpretty/venv/lib/python3.8/site-packages/tox/util/pep517/backend.py True setuptools.build_meta __legacy__
.pkg: prepare_metadata_for_build_wheel> python /tmp/y/astpretty/venv/lib/python3.8/site-packages/tox/util/pep517/backend.py True setuptools.build_meta __legacy__
.pkg: get_requires_for_build_sdist> python /tmp/y/astpretty/venv/lib/python3.8/site-packages/tox/util/pep517/backend.py True setuptools.build_meta __legacy__
.pkg: build_sdist> python /tmp/y/astpretty/venv/lib/python3.8/site-packages/tox/util/pep517/backend.py True setuptools.build_meta __legacy__
wat: install_package> python -I -m pip install --no-deps --force-reinstall /tmp/y/astpretty/.tox/4/.pkg/dist/astpretty-2.1.0.tar.gz
wat: commands[0]> python -c 'print("hello world")'
hello world
.pkg: _exit> python /tmp/y/astpretty/venv/lib/python3.8/site-packages/tox/util/pep517/backend.py True setuptools.build_meta __legacy__
  wat: OK (1.38=setup[1.35]+cmd[0.03] seconds)
  congratulations :) (1.41 seconds)

real	0m1.613s
user	0m1.487s
sys	0m0.128s
```

this is because it has to ensure things are at a consistent state (and that costs a lot! it essentially has to rerun all of the build and installation) -- this is what would be necessary at all to have a working environment

and then you look at tox3, which doesn't even know that the cache changes when requirements change (in a way tox4 still doesn't in all cases (recursive deps, constraints, environment variables) as it's only solved for the basic, common cases) -- requiring `-r` all the time.  I'm not going to build a solution which is incorrect and broken in the common case.

and that doesn't even bring us to the cache problem, pre-commit needs to know *up front* whether one of its immutable environments is satisfied already, otherwise it must run extremely slow build commands every time.  consider just if you specified `.` as a dependency -- it must then index every file in your codebase and rebuild essentially every time you make a change.  really not a desirable behaviour.  consider if you specified `-r`, you'd have to have a very-specific pip-option-sensitive parser to read and recurse that.  consider if you specified a `package.json` -- now pre-commit needs to understand the nuances of npm dependency management.  consider `cargo.toml`, etc. etc.

so this is your final warning, please do not comment about this again or I will have no other choice but to prevent you from contributing.  I'm sorry it has come to this but I'm tired of your behaviour on this topic.
