### ISSUE TITLE
Feature request: pre-commit run check-only mode

### ISSUE THREAD

**Issue by arwedus** [pre-commit/pre-commit#2144]
Hello,

I'm not sure if this has been asked before. I'd like to run the `pre-commit run` command on our PRs and pushes with all hooks/checks (including e.g. the trailing whitespace fixer), but I do not want it to generate automatic fixes; we currently have not much code that is committed by a bot and the developers should run pre-commit locally but sometimes may not have installed it.

I'm missing a `--no-fixes` or `--check-only` option.

**Comment by asottile** [comment]
pre-commit just runs tools, it has no insight as to whether those tools make changes

even if it did, I would reject this feature -- embrace the formatters rather than making it annoying for your users.  computers are really good at fixing things and having to manually format stuff in response to a linter is extremely tedious and the main reason people hate linters

**Comment by sam-super** [comment]
FWIW (mostly for future-me the next time i search for this): if a file is changed by a hook, i have found pre-commit exits with a non-zero code. 

so although it might mutate the files, you can error in your CI environment based on the exit code (so the changes never get persisted and the PR fails). 

I'm not sure if the exit code is dependent on the hooks themselves or if pre-commit checks for file changes itself so YMMV.

**Comment by asottile** [comment]
this is in the docs on https://pre-commit.com so I'd recommend looking there instead!
