### ISSUE TITLE
Hook contribution & minor suggestions

### ISSUE THREAD

**Issue by Lucas-C** [pre-commit/pre-commit#218]
Hello,

I'd like to introduce you to 2 simple pre-commit hook I wrote:
https://github.com/Lucas-C/pre-commit-hooks

It felt really simple to write, cleanly architectured and easy to share with colleagues.
So thanks a lot for your work on this !

Now, I have some minor complains:

- **no support for local hook development** : I had to create an initial github repo and then hack my changes in `$HOME/.pre-commit/repoXXXXXX/py_env/local/lib/python2.7/site-packages/pre_commit_hooks/forbid_crlf.py` while working on it. There should be an easier way to do this !

- the **required sha** property in `.pre-commit-config.yaml` : combined to the pain point #-1 above, it was really annoying to have to update it each time I was committing a new version of my hook on github. Couldn't you defined **a default empty value meaning to track the lastest version** ? I know I could use tags to specify stable versions, but it doesn't fit a work-in-progress development situation.

- the lack of instructions on how to develop a hook: your docs **never mention the necessity to have a `setup.py` file with entry points defined**, while you actually need it as a `virtualenv` is used under the hood. My [commit history](https://github.com/Lucas-C/pre-commit-hooks/commits/master) illustrates how puzzling developping a hook can become :D

What's your take on all of those issues, and which features would you be ok to integrate given that someone would suggest a pull request ?

And again, thank you very much for this awesome hooks manager !

**Comment by asottile** [comment]
Hello @Lucas-C 

Nice hooks! If you want I'd suggest PRing http://github.com/pre-commit/pre-commit.github.io to add your hook to http://pre-commit.com/hooks.html or alternatively make a pull request to http://github.com/pre-commit/pre-commit-hooks

For local development you can change the repo path to a path on disk.  Such as:

```yaml
-   repo: /home/asottile/workspace/pre-commit-hooks
    sha: 9ce45609a92f648c87b42207410386fd69a5d1e5
    hooks:
    -   id: trailing-whitespace
```

I've used this approach before, it's a bit clunky since there isn't really an **editable** way do do this, but the next point should explain why it's not easy to make that work.

You can read my comment here about why **latest** isn't going to work (or it would work but it couldn't be performant / repeatable / always correct): https://github.com/pre-commit/pre-commit/issues/158

That is a good point about **setup.py**! I'll add a section to the docs about the requirements (since node and ruby also have their own similar requirements).

Thanks again!

**Comment by asottile** [comment]
Let me know what you think of the doc updates here: https://github.com/pre-commit/pre-commit.github.io/pull/43

**Comment by Lucas-C** [comment]
Thanks for your quick answer !

Knowing that the `repo`Yaml entry can point to a directory is really great !
Could you please add it in the "Creating new hooks" section of the docs ?

#158 was a very interesting read. I should have searched in the issues before complaining about it.
Anyway `pre-commit autoupdate` fits my use case, and again should deserve a place in the docs !

I commented on #43 : it's a nice improvement, but still not detailed enough in my opinion. There should be an explanation that the repo created will be `pip installed` and that `pre-commit` expect to find entry points matching `hooks.yaml`.

An again: awesome job on this. I'm going to push for using it at my company.

**Comment by asottile** [comment]
:+1: 

Here's another that should make autoupdate more obvious: https://github.com/pre-commit/pre-commit.github.io/pull/45

**Comment by asottile** [comment]
I think this is resolved now, feel free to reopen if I missed something :)

**Comment by Lucas-C** [comment]
No, definitively resolved !
