### ISSUE TITLE
Question: Run a hook against all the files of the repo 

### ISSUE THREAD

**Issue by jalvaradosegura** [pre-commit/pre-commit#2194]
Hello! 👋 

I'm trying to create a hook. So far I've been able to make it work as I want.

Right now I was wondering if there is any parameter that I can add to the .pre-commit-hooks.yaml file, that allows the hook to always run against all the files of the repo?

I don't actually need all the files. The final result of this hook, would be the user passing the name of a few files and the hook should always check those files before doing a push, regardless if those files were modified or not.

I have seen and tested, that there is an --all-files option when running pre-commit through the terminal, but I haven't been able to add that to the .pre-commit-hooks.yaml file.

Is there any way to achieve this? thank you beforehand, for everything.

**Comment by asottile** [comment]
there's a few dupes for this but admittedly they are hard to search for so I'll rehash what's been decided in those dupes

- this is intentionally not implemented
- pre-commit aims to help you make quick checks and most of the framework centers around doing minimal checks by only passing a subset of files
- as soon as you start to run on other files in the repository you break many of the speed guarantees of pre-commit
- you cannot expect all filenames to fit on a single command line due to commandline limits, so even if your goal is to run against every file in one go it's not going to work in the general case
- you _can_ escape this hatch by explicitly passing paths through `entry` or `args` -- but doing so will always put you into the slow path and will disable many of the benefits of using pre-commit (only running on staged contents, only running on files which are checked in, only running on merge conflicted files, etc.)
- usually you don't actually need this, write your hook to target the changed files (quick) and use `--all-files` in CI for the rare case when changing one file will trigger a failure in another

**Comment by jalvaradosegura** [comment]
Thanks for you great answer Anthony!

Right now I'm working on a package which references to the version of the package in different files. Files with different extension and everything. And sometimes when we update the version of the package we forget to update the version in all the places (python cases are easy to handle)

I created a `pre-commit` [hook](https://github.com/jalvaradosegura/version-checker) that is working for that use case. Which basically works by checking that a set of files defined in the `args` parameter contain the desired version

Is this hook too bad? I know that a lot of improvement can be done, but is the idea of this hook ok?

**Comment by asottile** [comment]
yeah seems a bit questionable

it sounds like your entire use case is replaced by `importlib.metadata.version`

**Comment by jalvaradosegura** [comment]
Oh I see, that works perfectly for python file cases!

But what about if we need to check the version in some `.md`, `.html` and maybe other kind of files, would the hook  make more sense in that case?

**Comment by asottile** [comment]
you would probably need to have a fixed set of arguments and then it would work

still probably a better idea for a test in a testsuite rather than a hook

**Comment by jalvaradosegura** [comment]
Thank you very much for your fast replies and your awesome job!
