### ISSUE TITLE
FR: set the cache path in the .pre-commit-config.yaml file

### ISSUE THREAD

**Issue by benthevining** [pre-commit/pre-commit#2217]
[According to the docs](https://pre-commit.com/#managing-ci-caches), pre-commit's cache location can be set with the environment variables PRE_COMMIT_HOME or XDG_CACHE_HOME. In my workflow, I'm using CMake with [CPM.cmake](https://github.com/cpm-cmake/CPM.cmake), which automatically fetches third-party dependencies at configure time, so I've already got a git-ignored `Cache/` folder set up in my repo's root. It would be very convenient if we could specify in the pre-commit config file, a path to use as the cache location, relative to the directory of the config file.

Thanks for the great work, this tool is a godsend!

**Comment by asottile** [comment]
the cache is meant to be shared and the option is intended for CI and not general use

**Comment by krpatter-intc** [comment]
> the cache is meant to be shared and the option is intended for CI and not general use

I just wanted to add to this closed issue as it was the closes to the feature request I was about to file.

If the cache directory could be specified that would allow me to directly use the pre-commits hooks _in CI_ on the server after a push.

Since they are not local to the repo, if I use it in CI, then my runner ends up with a copy of these hooks for every single repo. It would be extremely helpful to specify a path as a subdir of the repo (and put in my .gitingore) or a tempdir, so that I could use my precommit hook _on the server_ to make sure folks are running it before committing.

As it is, we currently duplicate our tox.ini and pre-commit settings and need to make sure the versions in both stay in sync

**Comment by asottile** [comment]
it can be, did you read the section in the docs about CI caches?

**Comment by krpatter-intc** [comment]
Nope, apologies, I completely missed that part. That's exactly what I needed. Thank you!!
