### ISSUE TITLE
Idea: Can verbose mode be augmented to spit out the full command line that is executed?

### ISSUE THREAD

**Issue by Wargazm** [pre-commit/pre-commit#2274]
Hello,
When running `pre-commit run --verbose` you see the `hook_id` displayed, and if the hook is run you also see the script output regardless of pass/fail.

It would be nice if, underneath `hook_id`, we could see the full command line that gets run by pre-commit.  This would be helpful in debugging, especially for users who are setting this up for the first time (as I am).

Thanks for your consideration!

**Comment by asottile** [comment]
it intentionally does not because when it used to people abused the arguments and modified the (intended to be immutable) cache

the intended way to inspect arguments is to leverage the [`repo: meta`, `identity`](https://pre-commit.com/#meta-identity) hook

in the future please search the issue tracker

**Comment by Wargazm** [comment]
Appreciate the response.  I searched "command line" in the tracker and didn't see anything obvious pop up (though now my question pops up so hopefully someone else will find it).  

I see some questions regarding the identity hook so I'll read them.  I will say that documentation on that meta hook is light - it's definitely not obvious that this is the intended method to debug command line issues.
