### ISSUE TITLE
Feature Request: Add to Documentation for `require_serial`

### ISSUE THREAD

**Issue by adam-grant-hendry** [pre-commit/pre-commit#2437]
### search tried in the issue tracker

parallel

### describe your issue

Even after reading [the docs](https://pre-commit.com/#hooks-require_serial) for `require_serial`, it was still a little unclear to me what was being run in parallel

> `require_serial` (optional: default `false`)
> if `true` this hook will execute using a single process instead of in parallel. _new in 1.13.0_

After reading [the issue that appears to have driven this](https://github.com/pre-commit/pre-commit/issues/510), I understood it to mean it runs the hook operation _on the files passed to it_ in serial.

- It would be nice to add a sub-section to the documentation to explain that we are not talking about _running separate hooks in parallel_, but _running the hook operation on the files passed to it_ in parallel.
- It would be good to specify _under what circumstances would you actually want to set this to `true`_.
- Lasty, it would be good to clarify whether this option is only to be used _when creating new hooks_ or if it applies to all hooks (including those published in repos) and whether it affects settings like `log_file: true`

I imagine something like this:

```markdown
By default, `pre-commit` runs all hooks sequentially in the order they are listed in the `.pre-commit-config.yaml`. 
However, since version `v1.13.0`, `pre-commit` runs each _individual hook operation_ on all the files passed to 
it in parallel. The is beneficial for the majority of cases since it means each hook will execute faster, but there are
some scenarios where this may present a problem:

- if a hook reads from other files not passed to it (e.g. a configuration file), or
- if a hook writes to other files not passed to it (e.g. a log file)

In the above cases, this may lead to a race condition or deadlock. In the event your hook needs to access the 
same file across multiple processes, you can specify the hook be run on files sequentially by passing

`require_serial: true`
```

### pre-commit --version

2.19.0

### .pre-commit-config.yaml

```yaml
N/A
```

### ~/.cache/pre-commit/pre-commit.log (if present)

N/A

**Comment by asottile** [comment]
feel free to send a PR -- the docs are at https://github.com/pre-commit/pre-commit.com

though I think it's not necessary to say that many words and that the current definition shouldn't be that surprising given pre-commit's output of one hook at a time

also much of your prose isn't correct -- it wouldn't lead to a deadlock or race condition if the underlying tool is written correctly (it's easy to atomically update files, and reading multiple files isn't a problem) -- really the only case that `require_serial` should be used is if the underlying tool itself uses multiprocessing (fork bomb).  there are some incorrect uses of `require_serial` when one desires "run me with all the files at once" (which is actually impossible due to commandline limits)
