### ISSUE TITLE
Pre-commit shallow cloning strategy fails to grab the tag (git itself does)

### ISSUE THREAD

**Issue by ssbarnea** [pre-commit/pre-commit#2610]
### search you tried in the issue tracker

yes, found two related closed issues

### describe your issue

As a user of ansible-lint [reported](https://github.com/ansible/ansible-lint/issues/2713) that the hook reported its own version incorrectly as `0.1dev1` I had to research what happens. This allowed me to find #2354 and #1593 which reported the same kind of issue across different python projects using setuptools-scm.

I did look at the cloning logic of pre-commit tool which attempts to perform a shallow cloning first and only if this fails tries to make a full one. I manually repeated the steps and discovered that its operation does not created any local tags, so not surprise that any project using setuptools-scm would have wrong versioning:

## Test using pre-commit internal cloning strategy
```shell
git init --template= ansible-lint
cd ansible-lint
git remote add origin https://github.com/ansible/ansible-lint
git -c protocol.version=2 fetch origin v6.8.7 --depth=1
git checkout FETCH_HEAD
git -c protocol.version=2 submodule update --init --recursive --depth=1
# done, now testing if we have any tags:
git tag --points-at HEAD
# ... ooops, no tag.
```

## Test using official git shallow cloning:
```shell
git clone --depth=1 --branch v6.8.7  https://github.com/ansible/ansible-lint
cd ansible-lint
git tag --points-at HEAD
v6.8.7
# So it worked fine as tag is present!
```

As seen, is not the shallow-cloning that is the source of the problem but the absence of the tag . When using a single git command to clone, this is added, but with the more complex logic of pre-commit, this is not added.

I guess that this issue could be avoided by including the tag addition in pre-commit internal shallow cloning strategy.

### pre-commit --version

2.20.0

### .pre-commit-config.yaml

```yaml
- repo: https://github.com/ansible/ansible-lint
    rev: v6.8.7
    hooks:
      - id: ansible-lint
```

**Comment by asottile** [comment]
feel free to send a patch -- but everything else seems to work fine without needing the actual tag metadata

`clone --branch` doesn't work because `rev` can be things other than named refs / branches

**Comment by asottile** [comment]
note that even if you "fix" this -- it won't work for `frozen` things (which'll just have a 40-char hash) -- setuptools-scm is kind of a flawed idea imo -- it's pretty easy to use `importlib.metadata.version` at runtime rather than needing to tie your distributions to your VCS

**Comment by webknjaz** [comment]
@asottile it reads the metadata in runtime but IIUC pre-commit `pip install`'s the repository, and `pip install` builds it from source. It is the build step that puts that version into the metadata in site-packages, not runtime trying to interact with Git.

`setuptools-scm` won't work for arbitrary commits, as you've correctly stated. But it works for Git archives produced from tags, which are available on GitHub by `.tar.gz` and `.zip` URLs. The idea is that there's a template file that Git pre-fills with metadata when `git archive` is run, and it has the tag that setuptools-scm can use.
`setuptools-scm-git-archive` used to be needed for this to work, but now `setuptools-scm` has this out of the box — the projects just need to have this `.git_archival.txt` file and an attribute for it in `.gitattributes`. The newer versions of Git can also produce better metadata.
Of course, pre-commit does not use those Git archives, which is why the only way to make this work is to additionally fetch the tags pointing to that commit.

@ssbarnea I think you should be able to check if there's a corresponding tag via `git ls-remote --tags https://.../.git` and then fetch it in your bugfix. Alternatively, you could just fetch all the tags without having this check.

**Comment by asottile** [comment]
`git archive` is also an optional feature and many git servers don't support it (including github) so that's not helpful either

**Comment by webknjaz** [comment]
> many git servers don't support it (including github)

It supports archives for tags and branches. Did you mean it doesn't support archives for arbitrary commits?

**Comment by asottile** [comment]
```console
$ git archive HEAD --remote=https://github.com/asottile/astpretty
fatal: operation not supported by protocol
```

**Comment by webknjaz** [comment]
Oh, I never knew about `--remote`. TIL. I was talking about URLs like https://github.com/cherrypy/cheroot/archive/refs/tags/v8.6.0.tar.gz separately from the pre-commit's context but in the context of setuptools-scm — these files are constructed via `git archive` internally.
Thanks for the explanation!

**Comment by ssbarnea** [comment]
My plan was to just create the tag if it did not look like a valid checksum. At least this approach does not add another network call.

**Comment by webknjaz** [comment]
Oh, I haven't thought about it, that should work. Although, it wouldn't be the same and may break expectations of some tools that would attempt to read something from that tag's description.
