### ISSUE TITLE
Allow dry-run of CLI autoupdate command

### ISSUE THREAD

**Issue by MHLut** [pre-commit/pre-commit#2785]
### search you tried in the issue tracker

dry-run, dry, check

### describe your actual problem

Sometimes you want to check whether your hooks are outdated without updating them, for example, in a CI job.

Assuming `.pre-commit-config.yaml` is our configuration file.

Could you add a flag to the `autoupdate` command (e.g., `--check`, `--dry`) to signal that there are updates available for hooks defined in the configuration file?

#### expected behavior

The dry-run mode would change the following functionality compared to the regular flow:

1. It doesn't alter the configuration file.
2. Instead, it returns a non-zero exit code ONLY when updates are available.
3. It changes some wording in the command output (see below).

An example use would be:

```sh
pre-commit autoupdate --check
```

Which would return a `non-zero return code` and optional feedback like so:

```
Checking https://github.com/pre-commit/pre-commit-hooks ... newer version is available.
Checking https://github.com/another-hook ... already up to date.
```

If there are no updates, the output doesn't change from what it currently is.

### pre-commit --version

3.1.0

**Comment by MHLut** [comment]
@asottile Hello, could you provide a reason for this decision? Several packages offer such an option (e.g., for Python: black, isort, flake8).

I also don't see what version control has to do with this.

I want to use a CI job as a reminder to run `pre-commit autoupdate` if there are updates. This sometimes happens when services like Dependabot update packages but not pre-commit hooks.

**Comment by asottile** [comment]
I don't care what other things do. carrying such complexity encourages a bad idea (your idea is also a bad one, it's going to fail on random things -- you might want to just use pre-commit.ci which will send you a pr automatically). I say `--check` in general is a bad idea because it gives curmudgeons a "supported" way to enable a negative user experience of "oh I don't trust the formatter so instead I'm going to make the computer tell you what to do and waste your time instead of just formatting your code".  I'm not going to encourage that nonsense and it's not even necessary because everything should be in version control anyway

if you use vcs you can still do your bad idea simply by running `git diff` but I don't need to maintain a complex feature just so you don't need to run `git diff`. so not only do I think the feature is a bad idea, you don't need it to accomplish what you want

**Comment by MHLut** [comment]
@asottile A neutral explanation without all the rudeness would have been fine. We're not enemies here.

**Comment by asottile** [comment]
there's no rudeness intended

**Comment by MHLut** [comment]
Related Dependabot issue: https://github.com/dependabot/dependabot-core/issues/1524
