### ISSUE TITLE
How is #2918 a dupe of #1073?

### ISSUE THREAD

**Issue by MicaelJarniac** [pre-commit/pre-commit#2919]
### search you tried in the issue tracker

dupe

### describe your actual problem

Just an honest question. I'd ask in #2918 but it was immediately closed. I'd also ask on a Discussions tab but there's none.

#2918 asks to implement an option to enable colors with `FORCE_COLOR`.
#1073 asks to implement an option to disable colors with `NO_COLOR`.

It seems to me that #1073 was closed because of the confusing behavior of `NO_COLOR=` and `NO_COLOR=0` also being considered as "`NO_COLOR` enabled".

Is this the reason why #2918 is considered a "dupe"? Due to the fact that `FORCE_COLOR=` and `FORCE_COLOR=0` would also be considered "`FORCE_COLOR` enabled"?

Also, why are closed issues immediately locked, with no room for discussion?
I had an honest question about the closing of the issue, and I didn't want to have to open another issue just to follow up with the question.
I wanted to understand what happened, so I can learn from it.
I really like this project, and I've even sponsored you with $36 in the past.
I want the project to succeed, and I want to help whenever I can.
Sometimes, all I can do is suggest features and ask questions, as I'm not as experienced as a developer as you are.
I take these opportunities to learn and figure out what makes a project great.
Sorry for opening another issue.

### pre-commit --version

pre-commit 3.3.3

**Comment by asottile** [comment]
>  with no room for discussion

it is tiring to reiterate already decided things -- it's fine you didn't find the duplicate, neither of your search terms really came up with that (though I did find it by digging through issues for "color")

> Also, why are closed issues immediately locked, with no room for discussion?

specifically because I do not want to further discuss foregone conclusions.  I have very limited time to work on open source and if I waste it all debating why I have previously declined features I both (1) don't have time to work on actually useful things and (2) lose energy in general for working on open source.  as it is right now I spend more than half of my open source time closing duplicates

> It seems to me that https://github.com/pre-commit/pre-commit/issues/1073 was closed because of the confusing behavior of NO_COLOR= and NO_COLOR=0 also being considered as "NO_COLOR enabled".

yes, `FORCE_COLOR` suffers from exactly the same problem.  even if it did not, there is already a documented and tested way to do things which works for both use cases.  having `NO_COLOR` (broken standard) + `FORCE_COLOR` (also broken standard) + `PRE_COMMIT_COLOR` (works correctly, is specific, is tested) is maintenance hell and adds to the confusion and complexity for users of the project.  "one way to do things" is what I try and stick to until there's a very very good reason to add "yet another way" -- and even then I'd work pretty hard to phase out the other one.  "other projects do it" is not a good reason -- lots of projects do foolish things and blindly following their precedence isn't helpful.

> I really like this project, and I've even sponsored you with $36 in the past.

appreciate it -- it certainly helps a little.

>  I'd also ask on a Discussions tab but there's none

`Discussions` is a failed github feature.  issues already serves that purpose and I don't need two places to check and/or generate notifications / duplicates from.

> I take these opportunities to learn and figure out what makes a project great.

not saying this project is "great" (though I'm certainly proud of it) -- but one thing I try very hard to do is not add features "just because".  there has to be a very good reason to add such a thing that gels with the rest of the framework.
