### ISSUE TITLE
Provide mechanism for running pre-commit without installing dependencies

### ISSUE THREAD

**Issue by stefanv** [pre-commit/pre-commit#3030]
### search you tried in the issue tracker

"without dependencies" | "install dependencies"

### describe your actual problem

I've now run into multiple contributors to our projects who are worried about having pre-commit install and run packages onto their system. They would prefer to manually install the dependencies, and have pre-commit only run them.

Would it be possible to provide a mechanism for doing so? E.g., one option would be to just generate, print, and (optionall?) run the command line instructions.

### pre-commit --version

n/a

**Comment by asottile** [comment]
pre-commit does not install to the system -- they are always installed in user space (this is intentional to avoid the fear of "installing random stuff to the system")

there are mechanisms to skip installing and those are documented in the pre-commit docs but they entirely miss the point of pre-commit and so they are the unsupported escape hatch

**Comment by stefanv** [comment]
Right, I know pre-commit doesn't install to the system. It's the escape hatch you mention I was looking for, and couldn't find in the docs. Can you give a hint on what it is called?
