### ISSUE TITLE
Can not install on Azure Devops due to Ruamel

### ISSUE THREAD

**Issue by dguidara** [pre-commit/pre-commit#3036]
### search you tried in the issue tracker

azure ruamel

### describe your issue

As mentioned in a ticket for ruamel, https://sourceforge.net/p/ruamel-yaml/tickets/484/ The author switched the readme format to CommonMark which is not supported in Azure Devops.   This is preventing install of precommit.  Precommit does not have a upperbound on ruamel.   The issue happens in 0.17.39 and above.   

Can we set a pinned upper bound until its fixed?  Otherwise, I can fork precommit and  use that. 

### pre-commit --version

all

### .pre-commit-config.yaml

```yaml
n/a
```

**Comment by asottile** [comment]
pre-commit does not depend on ruamel.yaml -- I suspect you must be using some hook that does (but it's impossible to tell because you put in zero effort in making a bug report including ignoring the issue template)

the docs show you how to override dependencies if needed -- please search there first and next time please put some effort into your report -- there's a reason for the template

**Comment by dguidara** [comment]
> pre-commit does not depend on ruamel.yaml -- I suspect you must be using some hook that does (but it's impossible to tell because you put in zero effort in making a bug report including ignoring the issue template)
> 
> the docs show you how to override dependencies if needed -- please search there first and next time please put some effort into your report -- there's a reason for the template

apologies. precommit-hooks does.  I opened the issue in the wrong repo run by precommit.
