### ISSUE TITLE
How to use it in local machine pre-commit for multiple repos

### ISSUE THREAD

**Issue by sureshpdevops45** [pre-commit/pre-commit#3251]
### search you tried in the issue tracker

How to use it in local machine pre-commit for multiple repos

### describe your actual problem

How to use it in local machine pre-commit for multiple repos, i want to use as global pre commit for all repos in my local. i want to call the pre-commit from one location and will be used for all repos and this need to be done with any command. for all developers in my team.
we can achieve this in jenkins CI, but i want to so in local for all developers and individually also. can you please tell how this can be configured.

### pre-commit --version

pre-commit 3.7.1

**Comment by asottile** [comment]
pre-commit intentionally does not support centralized configuration as each repository will tend to have it's own unique needs

pre-commit the tool can be installed and shared across repositories though -- but that's on you to figure out which installation mechanism works best for you

note there are unsupported ways of configuring pre-commit in a centralized manner through `--config` (and or symlinks, submodules, etc.) though those are not recommended because they provide a significantly worse experience

there are quite a few duplicates which touch on the topic with examples

**Comment by sureshpdevops45** [comment]
Thank you for your reply.

How to configure the pre-commit by using the below methods.

--config (and or symlinks, submodules, etc.)

**Comment by asottile** [comment]
you need to try something first for me to help you.  I am not going to guide you to a solution in explicitly unsupported territory

**Comment by sureshpdevops45** [comment]
using submodule, how this can be done. as we are not doing .git folder version controlled. how this can be done?

**Comment by asottile** [comment]
are you looking for [`pre-commit init-templatedir`](https://pre-commit.com/#pre-commit-init-templatedir) ?

**Comment by sureshpdevops45** [comment]
I am looking for one central solution for pre-commit in multiple repos in local system. not on remote?

**Comment by asottile** [comment]
sorry, can't help -- please reread my messages and maybe you'll be able to help yourself
