### ISSUE TITLE
coala

### ISSUE THREAD

**Issue by sils** [pre-commit/pre-commit#340]
Hi,

we are currently writing a language independent static code analysis framework named coala - coala-analyzer.org . As part of that goal we offer a unified user interface to lots of common linters and provide stuff like json output and so on for them.

I think pre-commit could profit from coala in that you would not have to maintain that many tool integrations anymore since coala could act as a proxy here (we do that anyways). On long term that is less work for you and for your users because they can configure everything in one config file, don't need to learn multiple tools.

Is there any interest in making a coala integration happen?

**Comment by sils1297** [comment]
You can ping me on https://gitter.im/coala-analyzer/coala about this also if you want :)

**Comment by asottile** [comment]
I think coala is actually a step in the opposite direction (towards the approach that overcommit uses) in that it requires the consumer to set up a bunch of systems on their system: http://coala.readthedocs.org/en/latest/Users/Install/

I think it'd actually benefit you guys to use the plumbing of pre-commit (which we unfortunately haven't split out yet) which sets up environments for different programming languages so the end user doesn't have to worry about installing X package and Y language

Because we isolate hook repositories from each other in virtualenvs, it's pretty easy to add any tool which is installable (at least in the supported languages (which we'd love to expand on!)) -- in a sense pre-commit can proxy to any tool.

We don't actually have any "integration" so to speak beyond "you're an executable, I will run you with xargs" so beyond that I don't know what an integration with coala would look like.

I'm sick today, I should really get back to bed, let me know what you think :D

**Comment by asottile** [comment]
We also support py26, py27 -- it seems coala only works under python 3?

**Comment by sils1297** [comment]
Oh yes, coala is python 3 only, in that case that won't work I guess. We use annotations to simplify writing custom analysis routines, you get parameters converted directly into your types.

**Comment by sils1297** [comment]
> I think it'd actually benefit you guys to use the plumbing of pre-commit (which we unfortunately
> haven't split out yet) which sets up environments for different programming languages so the end
> user doesn't have to worry about installing X package and Y language

A universal package manager working on all platforms? Want that.

> We don't actually have any "integration" so to speak beyond "you're an executable, I will run you with xargs" so beyond that I don't know what an integration with coala would look like.

Ah ok. I'm very stressed right now but really wanted to file the bug, will look closer when a few things go by. (Sorry)

**Comment by asottile** [comment]
Going to close this for now, if the situation changes in the future, definitely feel free to reopen! :)
