### ISSUE TITLE
Error `pre-commit` not found. Did you forget to activate your virtualenv?

### ISSUE THREAD

**Issue by gabriel** [pre-commit/pre-commit#359]
If you commit using Github app, you get this error:

![2016-03-25 at 1 29 pm](https://cloud.githubusercontent.com/assets/2669/14053351/df080380-f28d-11e5-9b4f-1cd0152aa4eb.png)

**Comment by gabriel** [comment]
For UI's to work you'll need to tell launchd the python path:

For example, this fixed my problem:
```
launchctl setenv PYTHONPATH "/usr/local/Cellar/pre-commit/0.7.6/libexec/lib/python2.7/site-packages:/usr/local/Cellar/pre-commit/0.7.6/libexec/vendor/lib/python2.7/site-packages"
```

This applies globally though so maybe your use of virtualenv is a problem?

**Comment by gabriel** [comment]
Also seems like the PATH set through `launchctl setenv PATH` isn't respected

**Comment by asottile** [comment]
@gabriel can you show the output of:

`cat .git/hooks/pre-commit | grep '^ENV_PYTHON='` and
`head -n1 "$(which pre-commit)"`

?

**Comment by gabriel** [comment]
```
> cat .git/hooks/pre-commit | grep '^ENV_PYTHON='
ENV_PYTHON='/usr/bin/python'
```

```
#!/bin/bash
```

**Comment by gabriel** [comment]
To clarify more, this is using the Github Desktop app: https://desktop.github.com/

**Comment by asottile** [comment]
Hmmm, neither of those make sense to me -- where did you install pre-commit from?

For me they look something like this:

```
$ cat .git/hooks/pre-commit | grep '^ENV_PYTHON='
ENV_PYTHON='/home/asottile/workspace/pre-commit/venv-pre_commit/bin/python'
```
```
$ head -n 1 "$(which pre-commit)"
#!/home/asottile/workspace/pre-commit/venv-pre_commit/bin/python
```

Your output indicates that the `pre-commit` executable is a bash file whereas I expect it to be a python file.

**Comment by gabriel** [comment]
Installed through brew... I uninstalled from brew and used `curl http://pre-commit.com/install-local.py | python` and it seems to be fixed

I guess a problem with brew install?

**Comment by asottile** [comment]
I'll see if I can improve the brew installation experience though :)

**Comment by asottile** [comment]
I looked some more into this and they package pre-commit as a bash script with PYTHONPATH overrides.  I don't think it'll be easy to make this work with brew so I'm going to close this.

**Comment by asottile** [comment]
An update to this, they've improved the setup so I believe this works now \o/

**Comment by UrszulaCzerwinska** [comment]
I encounter the same error working with VS code in a virtualenv conda environment. If I try to use integrated SOURCE CONTROL:GIT in VS code.
I am using pre-commit @ https://github.com/pre-commit/pre-commit/archive/v1.14.1.zip

Any clues how to solve it?

![Capture](https://user-images.githubusercontent.com/3660462/85123162-0c1ec300-b228-11ea-80e2-769fcaa213e5.PNG)

Logs:

```
> git commit --quiet --allow-empty-message --file -
`pre-commit` not found.  Did you forget to activate your virtualenv?

````

**Comment by asottile** [comment]
1.14.1 is extremely old, so maybe start by upgrading to a newer version?

this issue is specific to brew however so yours is off topic

**Comment by bartkowiaktomasz** [comment]
For me it helped to install using `brew` (on Mac):
```
brew install pre-commit
```

**Comment by m-richards** [comment]
This seems to still be a problem on for Github Desktop on windows, with WSL installed. Github desktop apparently runs pre-commit scripts using WSL (https://github.com/desktop/desktop/issues/12562) (can test this by putting a `pwd` in the `.git/hooks/pre-commit` script generated by `pre-commit install`)

As a note for anyone else trying to fix this, I was able to fix by pip installing pre-commit on linux and running `pre-commit install` there, so that the WSL/ Github Desktop case satisfies the if, and the windows powershell/ git bash meets the elif to invoke the hooks. 
```bash
if [ -x "$INSTALL_PYTHON" ]; then
    exec "$INSTALL_PYTHON" -mpre_commit "${ARGS[@]}"
elif command -v pre-commit > /dev/null; then
    exec pre-commit "${ARGS[@]}"
else
    echo '`pre-commit` not found.  Did you forget to activate your virtualenv?' 1>&2
    exit 1
fi

```

**Comment by asottile** [comment]
@m-richards can you try the latest master revision? I think I fixed this already

**Comment by m-richards** [comment]
@asottile Thanks for the quick response, you're indeed right, thank you.
`pip install git+https://github.com/pre-commit/pre-commit@master` seemed to only install the 2.16 release, but cloning and locally installing master with `pip install -e .` did work, so that's great. 

There is still one niche edge case I came across, running `pre-commit install` from powershell works fine and `.git/hooks/pre-commit` starts with 
```bash
#!/bin/sh
#!/usr/bin/env bash
# File generated by pre-commit: https://pre-commit.com
```
but if I run pre-commit install with git bash,  `.git/hooks/pre-commit` starts with 
```bash
#!/usr/bin/env bash
# File generated by pre-commit: https://pre-commit.com
# ID: 138fd403232d2ddd5efb44317e38bf03
```
(no double shebang) and github desktop runs that with WSL, complains about CRLF line endings and on manually changing that fails as above.

**Comment by asottile** [comment]
the shebang there from git bash is from the old version
