### ISSUE TITLE
Detect the python version when creating `default` py_envs

### ISSUE THREAD

**Issue by insasho** [pre-commit/pre-commit#365]
Given two separate virtualenvs, one running with python3 and the other running with python2, and each with the appropriate pre-commit installed (`pip install pre-commit` in the first, `pip3 install pre-commit` in the second), the check-ast plugin fails to parse Python 2 (or 3) syntax correctly, depending on which virtualenv pre-commit was installed in first.

Suggestions: 
- the ~/.pre-commit cache should instead be a per virtualenv cache, rather than per user.
- instead of maintaining the cache, consider just using pip dependencies instead.

Example failure in Python 2 venv if Python 3 venv installs pre-commit first:

```
p2/main.py: failed parsing with python3.4:

    Traceback (most recent call last):
      File "/home/ubuntu/.pre-commit/repo_3mr61_f/py_env-default/lib/python3.4/site-packages/pre_commit_hooks/check_ast.py", line 23, in check_ast
        ast.parse(open(filename, 'rb').read(), filename=filename)
      File "/usr/lib/python3.4/ast.py", line 35, in parse
        return compile(source, filename, mode, PyCF_ONLY_AST)
      File "p2/main.py", line 178
        except socket.error, e:
                           ^
    SyntaxError: invalid syntax
```

Example failure in Python 3 venv if Python 2 venv installs pre-commit first:

```
p3/__main__.py: failed parsing with python:

    Traceback (most recent call last):
      File "/home/ubuntu/.pre-commit/repoCzM4lg/py_env-default/local/lib/python2.7/site-packages/pre_commit_hooks/check_ast.py", line 23, in check_ast
        ast.parse(open(filename, 'rb').read(), filename=filename)
      File "/usr/lib/python2.7/ast.py", line 37, in parse
        return compile(source, filename, mode, PyCF_ONLY_AST)
      File "p3/__main__.py", line 30
        "c=%s" % args.c, file=sys.stderr)
                                ^
    SyntaxError: invalid syntax
```

`rm -fr ~/.pre-commit` was run between each test.

**Comment by asottile** [comment]
So the initial implementation stored the "cache" once per repository (in `./.pre-commit`) but this posed several problems:
- shebangs were too long (caused errors on posixlikes)
- Every repository had copies of the hooks and would have to install them quite often (performance)

So in order to fix the shebang issue, the "cache" was moved to the homedir.

We also hit the issue described in our repositories, the fix we've been suggesting is when working in an environment where multiple python versions are used make sure to explicitly pin the python version for the relevant hooks using http://pre-commit.com/#overriding-language-version

That said, I think we can continue to use the homedir approach and be slightly more intelligent when receiving the [default](https://github.com/pre-commit/pre-commit/blob/da7e85c851a7ffd946d68547c0e378ca9d103fb5/pre_commit/languages/python.py#L60) python version -- perhaps detecting it from `sys.executable` + `sys.version_info`.

**Comment by ulope** [comment]
I just ran into this as well but in my case with Python 3.5 and 3.6 and the new `f""` syntax. 

I'd happily trade the overhead of duplicated installs for every repo against such cases of cross-project "contamination". Could this behaviour perhaps be an option to the install command?

**Comment by asottile** [comment]
I'm planning to improve detection so it'll *just work* without needing to complicate the cli / option interface.

Notably:

> That said, I think we can continue to use the homedir approach and be slightly more intelligent when receiving the [default](https://github.com/pre-commit/pre-commit/blob/da7e85c851a7ffd946d68547c0e378ca9d103fb5/pre_commit/languages/python.py#L60) python version -- perhaps detecting it from sys.executable + sys.version_info.

**Comment by asottile** [comment]
Finally getting around to this: #556

**Comment by asottile** [comment]
This change is in 0.15.1!
