### ISSUE TITLE
Faster (than) git clone

### ISSUE THREAD

**Issue by Lucas-C** [pre-commit/pre-commit#391]
Hi,

I was wondering how `pre-commit install` execution time could be improved.
Especially, I was considering the [`git clone` command employed](https://github.com/pre-commit/pre-commit/blob/eb2ac28f20d8732ccdb60bb41efe0acf71165fdf/pre_commit/store.py#L142-L152) to retrieve pre-commit hooks repos.
Hence a few questions:
- is there any specific reason to fetch the whole repo ? A necessity to have its full commit history fetched ?
- could it be considered to only retrieve a single commit ?
  Using for exemple one of the 2 methods mentioned here: http://stackoverflow.com/a/26957305/636849
- could we add a heuristic that retrieve archives from Github repos ?
  cf. https://developer.github.com/v3/repos/contents/#get-archive-link

```
https://github.com/User/repo/tarball/$sha
https://github.com/User/repo/zipball/$sha
```
- maybe advise hooks repo owner to `git bundle create` their repos to make cloning faster ?

I'm not git specialist, but I think some improvment could be done without much cost (simply adding `--depth 1` to the `git clone` may be an easy win).

**Comment by chriskuehl** [comment]
`git archive` would work pretty well here, but GitHub doesn't support it :\

**Comment by asottile** [comment]
`autoupdate` attempts to retrieve the history so that would have to be changed.  `git archive` is one potential way to improve cloning speed (however cloning speed is _usually_ dwarfed by virtualenv setup).  The approach for `autoupdate` could be changed to `git ls-remote`, but it may be more difficult than the current approach.

**Comment by asottile** [comment]
Ah, if `git archive` is not supported by github, then there isn't really anything better that's universal

**Comment by Lucas-C** [comment]
Are you ok if, as I starting point, I send a PR adding logs for the execution time of both git cloning & virtualenv setup ?

**Comment by asottile** [comment]
Summarizing some of the investigation in #628 

We attempted `--depth=1` for cloning and this hit two key snags:
1. If the revision in `.pre-commit-config.yaml` is not exactly master's sha, after cloning [checkout will fail](https://github.com/pre-commit/pre-commit/pull/628#issuecomment-331517451)
2. `autoupdate` works by inspecting history, there's no history when cloning with `--depth=1`

The test suite initially didn't highlight this due to `git clone /file/path` not supporting `--depth=1`.  This was adjusted in #629 and demonstrates failures with `--depth=1` in tests/commands/autoupdate_test.py (which seems to be the only tests which really exercised 1. above as well)

Cloning with `--depth=1` *is fast*, but we need to make sure it works correctly for the cases above.

**Comment by asottile** [comment]
This may be useful, though it is only available if the remote enables it and a sufficiently new version of git is used:

- https://stackoverflow.com/a/30701724/812183

Also `git fetch --depth=1` is a thing that could fetch tags.

If we're willing to complicate this to achieve some performance perhaps we could do something like:

1. clone shallow
2. try and fetch single revision (allow failure for old git / non-configured remote)
3. try and reset (success: fast track, failure: fall back)
4. try and shallow fetch tags
5. try and reset (success: fast track 2, failure: fall back)
6. fetch `--unshallow`
7. reset or error

**Comment by asottile** [comment]
Going to close this for now since I don't think there's anything currently actionable -- if not, please feel free to reopen :)

**Comment by tgross35** [comment]
In case anybody has time to make a PR: most repos are on github, and their API now allows you to list matching refs that are either tags or commits. This allows you to get the SHA for any ref, which you could then shallowly clone via. Also would allow autoupdate to scan for the latest tags via `GET /repos/:owner/:repo/git/refs/tags`.

Regarding auth, unauthorized users can make 60 requests per hour which is likely plenty for most people. If the requests fail, could fall back to the current method, or allow an API key to be stored somehow.

**Comment by asottile** [comment]
it's not actually relevant -- we implemented a fast shallow fetch using protocol v2 in #958 -- hitting the api would be even slower
