### ISSUE TITLE
Known issue: appveyor is currently failing

### ISSUE THREAD

**Issue by asottile** [pre-commit/pre-commit#511]
See upstream bugs:
- https://github.com/git-for-windows/git/issues/1106
- https://github.com/appveyor/ci/issues/1428

**Comment by asottile** [comment]
https://github.com/git-for-windows/git/issues/1106 is resolved
https://github.com/appveyor/ci/issues/1483 tracks the updates to appveyor

**Comment by elaichi** [comment]
I was demoing `pre-commit` to my manager and he immediately noticed the "failing" status on the homepage. I then had to explain that "the issue is actually with their CI", etc, etc, "trust me, it's a really cool project", etc, etc.
Glad to see that this is almost fixed :)

![pre-commit_by_yelp](https://cloud.githubusercontent.com/assets/1084792/24913776/31a42fc6-1ea0-11e7-8a68-819b7abd154a.png)

**Comment by asottile** [comment]
This is the new issue to watch: https://github.com/appveyor/ci/issues/1482

**Comment by asottile** [comment]
I think this is the new issue to watch: https://github.com/appveyor/ci/issues/1542

**Comment by asottile** [comment]
Yay it looks fixed!  Going to retrigger a job so our badge goes green again: https://ci.appveyor.com/project/asottile/pre-commit/build/job/8ije5h0y9nklpytr

**Comment by asottile** [comment]
All green!
