### ISSUE TITLE
Add search to the documentation

### ISSUE THREAD

**Issue by Haroenv** [pre-commit/pre-commit#659]
Hey 👋 I just found out about `pre-commit` and it seems like a really useful tool. However I noticed that there are a lot of options, and it might be hard to find it. 

I'm working at Algolia and we offer [docsearch](https://community.algolia.com/docsearch) as a free service for open source projects. It basically crawls the documentation and makes it searchable, and you add an autocomplete to your page so people can search in it. 

Let me know if you're interested!

**Comment by asottile** [comment]
If it's easy to add and adds a clear benefit I'd be open to adding it, if you'd like to get started on trying something like this the [docs are hosted here](https://github.com/pre-commit/pre-commit.github.io)

Note that [we already had a discussion about search and decided it probably wasn't worth it because the docs are one page](https://github.com/pre-commit/pre-commit.github.io/issues/49#issuecomment-103970885)

I'm going to close this issue, please open one on the documentation project for consideration: https://github.com/pre-commit/pre-commit.github.io

Thanks for the issue!

**Comment by s-pace** [comment]
Glad to help.

Congratulations, your search is now ready!
I've successfully configured the underlying crawler and it will now run every 24h.

You're now a few steps away from having it working on your website:
- Copy the following CSS/JS snippets and add them to your page


<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/docsearch.js@2/dist/cdn/docsearch.min.css" />

<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/docsearch.js@2/dist/cdn/docsearch.min.js"></script>
<script type="text/javascript"> docsearch({
  apiKey: '5f052a6b9f5c2b81614512796afa7000',
  indexName: 'pre-commit',
  inputSelector: '### REPLACE ME ####',
  debug: false // Set debug to true if you want to inspect the dropdown
});
</script>

- Add a search input if you don't have any yet, and update the inputSelector value in the code snippet to a CSS selector that targets your input field.
- Optionally customize the look and feel by following the DocSearch documentation (https://community.algolia.com/docsearch/documentation/)
- You can also check your configuration in the github repo (https://github.com/algolia/docsearch-configs/blob/master/configs/pre-commit.json). Feel free to open pull requests!

Feel free to get back to us if you have any issues or questions regarding the integration.
We'd also be happy to get your feedback and thoughts about DocSearch - so we can continue to improve it.

Have a nice day :)
