### ISSUE TITLE
Print actual files being fixed by hooks

### ISSUE THREAD

**Issue by bagerard** [pre-commit/pre-commit#681]
Hi,

First of all thanks for pre-commit, it's awesome!
While running isort as a hook, I noticed that it wasn't printing the files being fixed which isn't handy IMO. I could do a PR in isort but I thought it could be integrated in pre-commit. In fact, the current behaviour is that it prints "Files were modified by this hook. Additional output:" whenever a hook modifies a file, but it does not print the actual files.

I believe it could be useful to print the files being changed and not relying on the hook to do so. I think I can do that by parsing the output of "git diff --no-ext-diff" and extract filenames. The only issue I see is that it will be redundant with hooks that are printing that already (like autopep8-wrapper). Another option would be to print the modified files only if the hook returned empty stdout/stderr.

Let me know what you think, I'd be happy to work on this. If you don't like it, no problem I'll just do a PR in isort. Thanks!

**Comment by asottile** [comment]
One option that might help _today_ (without any changes) -- there's a `--show-diff-on-failure` option to [`pre-commit run`](http://pre-commit.com/#pre-commit-run).  One example usage of that is in [`tox`'s invocation for CI](https://github.com/tox-dev/tox/blob/20a3a781203e41fa13ff45a99bed800e07197f9d/tox.ini#L38)

Ideally, `isort` _should_ produce some sort of output when it modifies things, the best case scenario I can see from this issue is someone (we?) contribute back some fixes to `isort` itself to improve the situation there.

Here's the original PR which added this btw: #305

**Comment by asottile** [comment]
(also (shameless plug) you may find [`reorder_python_import`](https://github.com/asottile/reorder_python_imports) to have more pre-commit friendly output -- though it has different configuration (and way fewer options (intentionally?)) than isort)

**Comment by bagerard** [comment]
OK, I'll do a PR in isort and hope it will be integrated. I agree that it should be in isort anyway. I actually started looking at reorder_python_import first, but then switched to isort due to https://github.com/asottile/reorder_python_imports/issues/8
Thanks for the quick feedback!

**Comment by asottile** [comment]
Cool, if you want any help working on isort I've poked their codebase a few times and might be able to help with a PR :)

**Comment by bagerard** [comment]
That's very nice of you but I was interested in implementing that (minor) feature. I just opened a PR in isort, let's see if it gets accepted
