### ISSUE TITLE
conda <--> pre-commit

### ISSUE THREAD

**Issue by amelio-vazquez-reina** [pre-commit/pre-commit#701]
I run into an interesting error related to SSL:
```
$ git commit -m "test"
[INFO] Installing environment for git://github.com/pre-commit/pre-commit-hooks.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
An unexpected error has occurred: CalledProcessError: Command: ('/Users/avazquezreina/.cache/pre-commit/repor6iew_wd/py_env-python3.6/bin/python3.6', '/Users/avazquezreina/.cache/pre-commit/repor6iew_wd/py_env-python3.6/bin/pip', 'install', '.')
Return code: 1
Expected return code: 0
Output:
    Processing /Users/avazquezreina/.cache/pre-commit/repor6iew_wd
    Collecting flake8!=2.5.3 (from pre-commit-hooks==1.2.0)
      Could not fetch URL https://pypi.python.org/simple/flake8/: There was a problem confirming the ssl certificate: Can't connect to HTTPS URL because the SSL module is not available. - skipping

Errors:
    pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
      Could not find a version that satisfies the requirement flake8!=2.5.3 (from pre-commit-hooks==1.2.0) (from versions: )
    No matching distribution found for flake8!=2.5.3 (from pre-commit-hooks==1.2.0)


Check the log at /Users/avazquezreina/.cache/pre-commit/pre-commit.log
```

This is what I have:
```
$ python --version
Python 3.6.2 :: Anaconda custom (x86_64)

$ python -c "import flake8; print(flake8.__version__)"
3.3.0

$ brew install openssl xz
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (caskroom/cask).
No changes to formulae.

Warning: openssl 1.0.2n is already installed
Warning: xz 5.2.3 is already installed
```

**Comment by asottile** [comment]
This looks like a poor interaction between anaconda and virtualenv.  At least on macos I'd suggest using pre-commit through `brew` (or through a `virtualenv` using brew `python3` or python.org `python3` installers).

**Comment by amelio-vazquez-reina** [comment]
Thanks @asottile If you don't me asking, why does pre-commit use `virtualenv`?

**Comment by asottile** [comment]
The first section on [pre-commit.com](https://pre-commit.com) briefly covers this but I'll go in more depth :)

- pre-commit aims to need _zero_ things installed at the system level -- that is, I shouldn't need a sysadmin to manage ruby / scss-lint / flake8 / etc. at the system level in order to use industry-standard linters in a project
- projects encode the desired versions in a pre-commit configuration and they are (mostly) repeatable.  this means that the repositories linters will continue to pass irrelevant of external changes (whether they be system changes, or external changes).  This necessarily means that each repository may choose a different version of linters.
- in the python ecosystem, `virtualenv` is the natural choice for creating isolated environments to install python packages in.

pre-commit also aims to be a *user* tool, and not a system tool -- the linters it installs are all installed in user space and shouldn't interfere with the system.

**Comment by amelio-vazquez-reina** [comment]
Thanks @asottile Makes sense. I wonder if:

1. The creation of an isolated environment should be an option (one could technically activate an environment before using pre-commit)

2. Creating a `conda` environment should be as straightforward (AFAIK) as creating one with `virtualenv`,  so it could perhaps be an option (moreover, the presence of `conda` is detectable). I mention this because technically and one can pip install packages within a `conda` (isolated, also at the user level) environment. If you point me to the relevant part of the code, I may be able to help

Does that make sense?

**Comment by asottile** [comment]
1. this is already implemented: [`system` hooks](https://pre-commit.com/#system) and also for convenience (since the two concepts are highly related): [repository `local` hooks](https://pre-commit.com/#repository-local-hooks).
2. I don't really have any interest in maintaining `conda` support -- the complexity is not worth it imo.  There's far more edge cases with `conda` than there are with `virtualenv`.  conda also cannot be distributed with `pre-commit` itself so it's hard to make it work out of the box.

That said, if you want to hack on a `conda` integration -- I'd suggest taking a look at the [`python` language](https://github.com/pre-commit/pre-commit/blob/master/pre_commit/languages/python.py) -- it would probably make the most sense to implement `language: conda` separately.

**Comment by asottile** [comment]
Seems a workaround for this is:

```bash
pip uninstall virtualenv
conda install virtualenv
```

**Comment by asottile** [comment]
Since:
- the core issue here is an upstream issue: conda <=> virtualenv interaction
- I have no interest in using conda myself

I'm going to close this issue.

That said, feel free to submit a patch for this and I'll definitely consider it :)

**Comment by asottile** [comment]
And _apparently_ you can now `conda install pre_commit` thanks to @nicoddemus!

**Comment by amelio-vazquez-reina** [comment]
Great news! Thanks @nicoddemus! and @asottile !

**Comment by nicoddemus** [comment]
:+1:
