### ISSUE TITLE
feature: check for .pre-commit-hooks.yaml when parsing local repo

### ISSUE THREAD

**Issue by jdswensen** [pre-commit/pre-commit#728]
When parsing `repo: local` in .pre-commit-config.yaml, pre-commit should check to see if the information exists in a local .pre-commit-hooks.yaml. Currently it does not, which can lead to duplication of the hook definition when making new pre-commit hooks repos.

**Comment by asottile** [comment]
Could you elaborate? I'm not sure I understand what you mean.  `repo: local` is intended for repository-specific hooks

**Comment by jdswensen** [comment]
I'm trying to develop a repo of [my own hooks](https://github.com/jdswensen/git-hooks) and I want to run one of the hooks I'm developing on the repo itself.

**Comment by asottile** [comment]
I believe you're looking for [`pre-commit try-repo`](https://pre-commit.com/#developing-hooks-interactively)?

(You can use `repo: /path/to/repository` too!)

**Comment by jdswensen** [comment]
I have looked at both of those, my problems with those are:

- `try-repo` assumes the code checked in to github already functions and exists. It also looks like its aimed more at testing an existing hook repo before adding the configuration to a project
  - I got this error when I tried with the local directory
```
$ pre-commit try-repo ./
[INFO] Initializing environment for ./.
An unexpected error has occurred: CalledProcessError: Command: ('/usr/bin/git', 'clone', '--no-checkout', './', '.')
Return code: 128
Expected return code: 0
Output: (none)
Errors: 
    fatal: repository './' does not exist
```
- `repo: /path/to/repository` would result in me hardcoding my local path on a public repo

I guess my confusion is related to the self referencing nature of the hooks. For example in the pre-commit-hooks [config](https://github.com/pre-commit/pre-commit-hooks/blob/master/.pre-commit-config.yaml), is there any design/architectural/design reason that `repo` couldn't change to say local instead of the github URL? If you are already self referencing, you would want to be using the latest changes, right?

**Comment by asottile** [comment]
How about `pre-commit try-repo "$PWD"`?

`try-repo .` should work too -- I wonder if that broke when I redid some `pwd` stuff.

**Comment by asottile** [comment]
Your other comment is also covered in a (planned) feature [here](https://github.com/pre-commit/pre-commit/issues/703)

**Comment by jdswensen** [comment]
"$PWD" works, "." did not. I can open another issue if you want.

Ahh, cool. What about the case where I'm developing these on an island and have no access to github? :)

**Comment by asottile** [comment]
`try-repo /path/to/repo` doesn't involve github (git is a distributed version control, `commit` is entirely local)

I have a fix for the other thing, coming right up!

**Comment by asottile** [comment]
Here's the fix for relative paths being unclonable -- it used to work but then I broke it oops! https://github.com/pre-commit/pre-commit/pull/729

**Comment by jdswensen** [comment]
Fair point. Even if I add a local filepath, I'm going to just use the path to where ever the repo is stored on my local filesystem (but now I need to specify a revision). I assume this is why `local` was developed in the first place. I think using `local` simplifies things when setting up a hook repo, cloning it, forking it, or move it to another location.

**Comment by asottile** [comment]
Please try out [v1.8.2](https://github.com/pre-commit/pre-commit/releases/tag/v1.8.2) with the `try-repo` fix!

**Comment by jdswensen** [comment]
I'm not expecting `local` clone anything, that's why I wanted to use it. My concern is that if I want to develop a shareable pre-commit hooks repo, I'm required to specify a central repo location (git url or file system location) in order to use the hooks in that repo, on that repo. If my code was in `/home/user/loc1` and moved it to `/home/user/loc2`, I would need to go change the config. Same if I moved from Github to Bitbucket or VSTS. Basically, if I wanted to move/push my code to several different places at the same time, all of those places would be referencing a single location instead of the repo itself.

**Comment by jdswensen** [comment]
My world won't come to an end if `local` isn't intended to be used this way. I just ended up repeating the pre-commit-hooks definition in the -config definition. It seemed redundant, which is why I opened the issue. If you're not planning to use it this way, that's ok too. I can close the issue if that's the case.

**Comment by jdswensen** [comment]
I was expecting this to work:
.pre-commit-config.yaml
```
repos:
-   repo: local
    hooks:
    -   id: local-id
```

.pre-commit-hooks.yaml
```
-   id: local-id
    name: <name>
    description: <Description of local-id>
    entry: path/to/local-id
    language: <language>
    files: <files>
```

Similarly, I would expect that the pre-commit-config.yaml from pre-commit/pre-commit-hooks would utilize `local` since it references scripts that are in its own repo. Like this:
```
repos:
-   repo: local
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: autopep8-wrapper
    -   id: check-docstring-first
    -   id: check-json
    -   id: check-yaml
    -   id: debug-statements
    -   id: name-tests-test
    -   id: requirements-txt-fixer
    -   id: flake8
-   repo: https://github.com/pre-commit/pre-commit
    rev: v1.7.0
    hooks:
    -   id: validate_manifest
-   repo: https://github.com/asottile/reorder_python_imports
    rev: v1.0.1
    hooks:
    -   id: reorder-python-imports
        language_version: python2.7
-   repo: https://github.com/asottile/add-trailing-comma
    rev: v0.6.4
    hooks:
    -   id: add-trailing-comma
-   repo: meta
    hooks:
    -   id: check-hooks-apply
- id: check-useless-excludes
```

**Comment by asottile** [comment]
Ok, where would `pre-commit` install the executables for those hooks?

**Comment by jdswensen** [comment]
Would you need to install them? For shell scripts I know you could just run from the local entry point, but if you need to generate a binary executable, you could create a `.cache` folder in the `.git` folder (or create one in the project root and add it to gitignore). I could see disadvantages with that if you needed to regenerate after each commit. Hmmm....

**Comment by jdswensen** [comment]
I suppose you could make the `rev` tag optional for `local` to avoid regenerating every time. If it is omitted, you regenerate with the most recent commit hash.

**Comment by asottile** [comment]
Ah I see, you're just working with `script` type hooks (one of the few "languages" supported by `repo: local`).  `script` hooks are by and far the _uncommon_ case.  The majority of hooks involve an isolated prefix environment (which is **git cloned** and then given a prefix environment (virtualenv / nodeenv / ruby environment / isolated gopath / etc.) inside `~/.cache/pre-commit`).

For the most part, `local` hooks are also the uncommon case (the rationale again is above and in the documentation), the golden path is really: specify a repository, it's version, and the hookids that you want to use -- the remote repository provides the thinking bits (what files does it apply to? what language is it implemented in? what is the executable? etc.) instead of needing to copy this information around everywhere.

Also, for testing your own hooks you _probably_ want to be testing them in the way that others will use your repository: via `repo: ...`.  This is why `try-repo` is designed to be as close as possible to how one would actually use a repository.  This is why [`pre-commit-hooks` _installs itself_](https://github.com/pre-commit/pre-commit-hooks/blob/e80813e7e9bceeb263a4329341f2681074fa725a/.pre-commit-config.yaml#L2-L3) -- even why [`pre-commit` installs itself](https://github.com/pre-commit/pre-commit/blob/834ed0f229a39c986b241374f6d338632e003b5f/.pre-commit-config.yaml#L15-L18) (a neat bit of history, pre-commit's first hook was actually [itself](https://github.com/pre-commit/pre-commit/commit/af7e23aae5eeb2503779efa858e57d7f22120360) -- v. meta).

I hope you understand why I don't want to extend `local` to also perform installation:
- there's already _designed_ ways to do what you want
- `local` has a documented purpose -- and it doesn't match this
- installation / invalidation of installation state would be nearly impossible
- pre-commit will not pollute your working directory with installations (not just because I find it impolite but also because it has [technical problems](https://github.com/pre-commit/pre-commit/pull/91) (pre-commit used to do this!))
- pre-commit is designed for _repeatability_, there are no ["floating version installs"](https://pre-commit.com/#using-the-latest-version-for-a-repository).

**Comment by jdswensen** [comment]
I completely understand, once I started digging into the other language operations it became clear why you designed things the way you did. Thanks for the patience and detailed explanation.

And yeah, I mostly write software for embedded Linux systems and microcontrollers, so I'm use being the uncommon case for things.

**Comment by asottile** [comment]
Cheers!  Thanks for hearing me out :) (and we even found and fixed a bug as part of this!)
