### ISSUE TITLE
Question: availability of check_mock_methods

### ISSUE THREAD

**Issue by hectorv** [pre-commit/pre-commit#734]
While thinking about Python mock's gotchas I wondered if pre-commit hooks already existed to check for some of them. That's when I found `check_mock_methods`, which unfortunately seems to be hosted in a private Yelp repo:
https://github.com/Yelp/osxcollector/blob/09a044824b89a03223f764e2caf6191cda8ed8da/.pre-commit-config.yaml#L19-L27
Given `pre-commit`'s relationship with Yelp, could it be possible to make it available in https://github.com/pre-commit/pre-commit-hooks ?
Thanks!

**Comment by asottile** [comment]
`pre-commit` is no longer associated with Yelp :)

fwiw, we decided `check_mock_methods` was obsolete when `mock>=1.1` introduced the following behaviour:

```pycon
>>> import mock
>>> x = mock.Mock()
>>> x.assert_has_three_calls()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/private/tmp/venv/lib/python2.7/site-packages/mock/mock.py", line 714, in __getattr__
    raise AttributeError(name)
AttributeError: assert_has_three_calls
```

(raising on invalid attributes that start with `assert` ([or `assret`, hilariously](https://github.com/python/cpython/blob/629338f1404ea9cd75e4fb0389a2fbe1b589de43/Lib/unittest/mock.py#L584))

Since it was deprecated internally, and since mock has improved behaviour, there's not much use in open sourcing it.

**Comment by hectorv** [comment]
Makes sense, thanks again!
