### ISSUE TITLE
Automatically stage files changed by hook

### ISSUE THREAD

**Issue by cellscape** [pre-commit/pre-commit#806]
Is there a way to automatically stage files changed by hook? For example black or prettier automatically reformat code and then pre-commit hook fails after detecting changed files. After that I have to manually stage changed files and run commit once again, unnecessary friction since formatting just works and changes are expected.

**Comment by asottile** [comment]
But then when it doesn't work it's too late to undo it :)

pre-commit takes a strong stance on never modifying the staging area -- you can read more [here](https://github.com/pre-commit/pre-commit/issues/747#issuecomment-386782080) (there's a few other issues as well about running `git add`).

Since software is imperfect in the general case, pre-commit will not commit anything until it has been looked at by a human.

Fortunately, `git add -u && !!` is pretty easy to run if you're ok firing from the hip :)

**Comment by travisdowns** [comment]
> Fortunately, `git add -u && !!` is pretty easy to run if you're ok firing from the hip :)

That adds all tracked files which have modifications, not just the ones updated by pre-commit. So maybe you'd wnat something like `git stash push -> git commit -> git add -u -> git commit again -> git stash pop`
