### ISSUE TITLE
Easy way to find hook repo?

### ISSUE THREAD

**Issue by firba1** [pre-commit/pre-commit#938]
Sometimes when I'm debugging hook failures, I need to introspect the hook's setup. For example, if I have a flake8 failure, then I want to figure out which flake8 version I'm installing in my pre-commit-hooks repo installation. Currently, `$XDG_RUNTIME_DIR/pre-commit/` contains a bunch of dirs with the hook repos, but no actual indication of which repo is which, leading to having to check each on individually. I think this could be solved in one of these ways:
1) put each repo in a predictable place, e.g. pre-commit-hooks v2.1.0 would end up in `$XDG_RUNTIME_DIR/pre-commit/github.com/pre-commit/pre-commit-hooks/v2.1.0/`
2) add a command to get directory of particular repo

**Comment by asottile** [comment]
You can inspect the private state information with `sqlite3 ~/.cache/pre-commit/db.db`

you can also temporarily override:

```yaml
    -   id: flake8
        entry: which flake8
```

That said, the installation is intentionally hidden away and supposed to be immutable, making it easier to muck with that is not going to happen.

Deep paths do not do well for shebang limits which is why there is a database implementing indirection, predictable paths are not feasible

**Comment by firba1** [comment]
fug
