### ISSUE TITLE
Colors

### ISSUE THREAD

**Issue by ghostsquad** [pre-commit/pre-commit#969]
I find the white on yellow color for hooks that have passed hard to read. Also, yellow typically means warning. Can the colors be configurable?

**Comment by asottile** [comment]
`Passed` is green not yellow, it uses whatever color your terminal emulator has configured for green.

For instance, this is what it looks like on ubuntu:

https://asottile.github.io/pygments-pre-commit/demo/test_basic_pre_commit.html

**Comment by ghostsquad** [comment]
Hmm but can this be made configurable? Like maybe the ability to remove the
background color?

Cheers,
Wes

**Comment by asottile** [comment]
yes, you can disable colors with [`--color=never`](https://pre-commit.com/#cli)

**Comment by avatar-lavventura** [comment]
> yes, you can disable colors with [`--color=never`](https://pre-commit.com/#cli)

Is it possible to change the font color?

my precommit `...PASSED` and `...Skipped` colors are as follows (font color is white where it is not readable on top of green background):

[![enter image description here][1]][1]

Here https://pre-commit.com/#usage, its much more readable:

[![enter image description here][2]][2]

**[Q]** How could I change the font and background color of `Passed` and `Skipped` that is located at the end of each check?

  [1]: https://i.stack.imgur.com/uQPvL.png
  [2]: https://i.stack.imgur.com/VEfns.png

**Comment by asottile** [comment]
the font color comes from your terminal emulator -- I have no control over it but you do!

**Comment by avatar-lavventura** [comment]
@asottile I do not know how does the readable colours in my local terminal config is set. Small example would be helpful

**Comment by asottile** [comment]
I literally can't know, I don't know what terminal emulator you are using there are thousands of them.  it's probably in your terminal preferences somewhere not in a dotfile on disk

**Comment by avatar-lavventura** [comment]
@asottile  I am using `zsh`

**Comment by asottile** [comment]
that's your shell, your terminal emulator is the program you launch on your computer (such as iterm or windows terminal or gnome-terminal, etc.)

**Comment by avatar-lavventura** [comment]
I am using `iTerm` that has dark background theme along with white foreground color. Does `Passed` pulling the foreground color? 

My configuration:
<img width="551" alt="image" src="https://user-images.githubusercontent.com/18537398/116809340-3169a680-ab46-11eb-9032-964628d9d694.png">

**Comment by avatar-lavventura** [comment]
I assume there is a configuration bug in pre-commit end that it is configured for the white background theme and dark background theme is ignored.

I am using `iTerm` that has dark background theme along with white foreground color. Does `Passed` pulling the foreground color? 

My configuration:
<img width="551" alt="image" src="https://user-images.githubusercontent.com/18537398/116809340-3169a680-ab46-11eb-9032-964628d9d694.png">

----

Afterwards, when I change foreground theme to something else than white, font color of `...Passed` is changed but it effects my overall font configuration. Font color should be white on my end since I am using dark background theme.

<img width="517" alt="image" src="https://user-images.githubusercontent.com/18537398/116816570-270dd380-ab6b-11eb-94a7-ed55710eae7c.png">


![](https://i.stack.imgur.com/EzUjz.png)
