### ISSUE TITLE
pre-commit should be able to run travis lint

### ISSUE THREAD

**Issue by ssbarnea** [pre-commit/pre-commit#970]
[Travis CI has a linter](https://support.travis-ci.com/hc/en-us/articles/115002904174?page=1#comment_360001572353) which can be very handy to run a pre-commit hook. Instlling the linter is done using `gem install travis --user-install --no-rdoc --no-ri` and running it is just as simple as `travis lint`.

I would propose a PR myself to add this but I currently do not know how to write pre-commit hooks for non python based projects, so some help would be appreciated, like link to something similar that uses "gems".

Update: @asottile You can assign it to me as I was able to succeed making it work. Now I only need to make a PR and convince travis to adopt the change.

Another question is: does this mean that I would not be able to use the hook before they will make a new release?

**Comment by ssbarnea** [comment]
And surprise there is a 3 years old PR for adding this hook to travis.rb at https://github.com/travis-ci/travis.rb/pull/307 

@asottile Can we add it in a different place if travis team does not react? They are notorious for  ignoring community contributions, this being just another example.

**Comment by asottile** [comment]
yeah we can, let's give it some time since the latest update

In the meantime there are several options:

1. use a local hook:

```yaml
-   repo: local
    hooks:
    -   (the same config that's in the PR) + `additional_dependencies: [travis...]`
```

2. Use one of the forks (point at a sha)

___

> Another question is: does this mean that I would not be able to use the hook before they will make a new release?

- When the PR above gets merged: `rev: <a sha1>`
- When a release is made then can switch to `rev: <a tag>`

___

For now I don't think there's much to do here, it isn't really a "framework" problem so I'm going to close this (there's also adequate workarounds)
