### ISSUE TITLE
Amend commit support

### ISSUE THREAD

**Issue by domenkozar** [pre-commit/pre-commit#999]
There are some checks that are automatic. We're using brittany (Haskell source formatter) and my workflow goes always as following:

1) make changes
2) commit
3) pre-commit failed
4) amend commit
5) commit again

I was wondering if 3 and 4 could be merged into pre-commit showing the diff and then asking to amend it?

**Comment by asottile** [comment]
It could, however pre-commit currently doesn't do either of the two things:
- modify the staging area
- have interactivity

The second is difficult as well because git hooks are not handed a tty and would have to (unreliably) fish one out of `/dev/tty` (not even sure this is possible on windows)

I use:

```bash
git add -u && !!
```

quite often fwiw

**Comment by domenkozar** [comment]
I guess interactivity was a stretch goal, I would be happy with just "accept the output" as there's nothing one can really do against autoformatter.

I presume modifying the staging area is doable?

**Comment by asottile** [comment]
one could `SKIP` / etc. to bypass the auto formatter.

pre-commit takes a strong stance on not modifying the staging area -- here's more reading on that subject: #747 #806 #879

**Comment by domenkozar** [comment]
Alright :)

**Comment by asottile** [comment]
thanks for the issue though!  :tada:
